# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openebs
  values:
    localpv-provisioner:
      enabled: false
    zfs-localpv:
      enabled: false
    lvm-localpv:
      enabled: true
    openebs-crds:
      csi:
        volumeSnapshots:
          # Installed with the Snapshot Controller
          enabled: true
          keep: false
    mayastor:
      enabled: false
    engines:
      local:
        lvm:
          enabled: true
        zfs:
          enabled: false
      replicated:
        mayastor:
          enabled: false
    loki:
      enabled: false
    alloy:
      enabled: false
    minio:
      enabled: false
