# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openebs
  values:
    crds:
      csi:
        zfsLocalPv:
          # -- Don't keep CRDs on chart uninstall
          keep: false
        volumeSnapshots:
          # use standalone Volume Snapshot CRDs
          enabled: false
          # -- Don't keep CRDs on chart uninstall
          keep: false
    zfsNode:
      encrKeysDir: "/var/openebs/keys"
      resources:
          limits:
              memory: 128Mi
          requests:
            cpu: 100m
            memory: 128Mi