# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openebs
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: openebs
  values:
    crds:
      lvmLocalPv:
        # Install lvm-localpv CRDs
        enabled: true
        # Keep CRDs on chart uninstall
        keep: false
      csi:
        volumeSnapshots:
          # Install Volume Snapshot CRDs
          enabled: false
          # Keep CRDs on chart uninstall
          keep: false