apiVersion: v1
kind: Secret
metadata:
  name: rustfs-secret
  namespace: storage-system
stringData:
  RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:OPXNyJy/gRr0lpU=,iv:PN4231RHzHUyGCAe9vr7Ufb+emKJLkHD+1yD2GI3txg=,tag:Z0XNJq5iR/aXPqoBhbvyVw==,type:str]
  RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:+Zg5sSFafWDnYT8=,iv:Q4Szpk/qn6/boTaNlTJyW4yj4yVGswnwld7aYrEC4e4=,tag:gNbSoTscBNYxcXv/gwhxbQ==,type:str]
  #ENC[AES256_GCM,data:7PZkEniUipYh5RRAjJ5gBNHfgj2KK/sQCiYCkSH64dqOexcIUzwSEkbr7sC7+o3lBpanrHZ3xRrsKnrlbra6uI8nVQ==,iv:F7f1kImdj3cdEs547slB2+zu6lcvIV4YWM459NjmWEQ=,tag:yymOSYvk8zgPnyBq5q0uOg==,type:comment]
  #ENC[AES256_GCM,data:xyPWzabmvSqAsEmgw3HFy4kKgbG9rXjsHwKOrKRtwkudXOC85S0c7ulr95XLaPvRGQeOilFb4LyQdSo9ya0N3OfagJxiLb5HLWQN,iv:a9LXqTADVrH2pDreh8f0UxAgoKvC/DBCh5BTcTK2OaM=,tag:vLHSfX/9pcwcuwjULXI/uQ==,type:comment]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcXd3ZDZMM3Q0elBCaVZw
        VjR0S0tJa2ZMcWdrVDRCbWVoeGNQSkRRYzFVCkxtRkFQS2JQRFUrVmJlRHRRcS92
        SU5vRkN6eSs2bitzMXBVS3F3cFJ0eGsKLS0tIElpN084SGpjN1pZTEdVZ3BNZEhZ
        SGpSdFZnc1lRTk1rd042UzZ0c1VLQ0kKQnaIe3uAD6lvV1hpZroDhK//1LgDpDCv
        kzTsY+WedCM0AvWq6FpgwGRBqBCzmrUxjCHe/6efKFLOc4+NXmIYpw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T19:30:17Z"
  mac: ENC[AES256_GCM,data:CaaPnF6n/4kZzvbWkQTpCQvpvZa014dmtJNxfOLyKcIt4z8kaU6Ju1b/w/in9MrS5FR6C9Y8ULMoX4YonK3UW2WSjYVyyhKe3pfMkLGp6qIcB2DwR/uktGMR4hmDMbMRJCQicVi+aaGduC6d/CvrrQ92bqJ5Mhwe7jS1r/ZbJk4=,iv:nHfjAvb6MGCotUFbk3SmF1m1/2hQpBI0ravKWj9urzg=,tag:7wtq3FtwMnk012yaRuY89A==,type:str]
  version: 3.13.2
