apiVersion: v1
kind: Secret
metadata:
  name: silo
  namespace: media
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:EhpKXEp/Uace+TT1u8NBzE6DWWQEnRpXQ1CfVAFhwlQiN53O8ZFU34Zo+kahCwrLXVcosofUTRfN51fksLH0DA==,iv:LGqqMhb3s0NK+YNKiIY7+qmErRvQq2POOUqeWIKjxcg=,tag:Voa5kh3Yuer9UoX75YOn8Q==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:WPQIwARD4S0fC1aNMm1j+n7VBSwNUoVj6HLdDZvBl0axIyq/rYLN/WndUNqeJ7uWHxEDrhrcMXF+zBXg2yDxBq4d7DZeyUA9Qmx19H+5KUHJWqjcOyBj6A==,iv:jku3My0uF6Z859+sO+/xmMdDdWwSrTnYW4fTg6Q3Pu8=,tag:wU5En8+RIWGYsx6kyrNPhA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeUF3UmZSWFQwcFRPajBq
        RytEU3NPR0NrcHhnZnZTcTJpV3owV0Y0VENjCjNwN2RTZUpTTDk1a2ZET0txSnU5
        NUxLczlOdFV2K2NMbDZSRXFzdXYvdWcKLS0tIGJaUEFFZzdMTkxocEkyc0ZTUEpI
        UkFKMDZZb202SGtoTDdTRG1KWWxwRW8Kz7K2vq0EEyo/+035IzS5Buw8JEgjxT34
        zT503wOGVYxbAFmNfoGs2v00+4csDdCtCGDcrIP/lsj0W2WaDu3vHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T15:29:51Z"
  mac: ENC[AES256_GCM,data:gKum0/7s296iO3tSTYEOEwkwwm2nDUu558c0q4ZbazVGb7xeL6gu2mzKQ5kX5nTvQt79m+P6aSnPr67kry9oICbIBNF+xBbFoVnZ3wg8APH68anHXb0ZeTwLo1qzfpilVQY9rzVH6tnk2mU7R0zG+Ohr8JPnrKUqHb9M9H9PWVY=,iv:qBjwTHBpJI187IG1ZyWk6/L2PboGNCOH7dNzV7IdyBU=,tag:JYixHdgbjZLfPf2R7Nc6ag==,type:str]
  version: 3.13.3
