apiVersion: v1
kind: Secret
metadata:
  name: silo
  namespace: media
stringData:
  SECRET_KEY: ENC[AES256_GCM,data:EhpKXEp/Uace+TT1u8NBzE6DWWQEnRpXQ1CfVAFhwlQiN53O8ZFU34Zo+kahCwrLXVcosofUTRfN51fksLH0DA==,iv:LGqqMhb3s0NK+YNKiIY7+qmErRvQq2POOUqeWIKjxcg=,tag:Voa5kh3Yuer9UoX75YOn8Q==,type:str]
  DATABASE_URL: ENC[AES256_GCM,data:GLB3toz0LERpMqzBtbc0ZzhhO/kQKD+EAkZ+/LAXzswywN059oVeTbgmf1eiBrU5MK9jQ5GTiJ12RUDxqHMAkOLqw8bKqvjN+TvN2W1TkXQ=,iv:67bl6I4htMBdpdef5kP1LSyT+POXqMDVYj5c1CR+ojA=,tag:OgWM8AALoHJx2QNshAw72w==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVeUF3UmZSWFQwcFRPajBq
        RytEU3NPR0NrcHhnZnZTcTJpV3owV0Y0VENjCjNwN2RTZUpTTDk1a2ZET0txSnU5
        NUxLczlOdFV2K2NMbDZSRXFzdXYvdWcKLS0tIGJaUEFFZzdMTkxocEkyc0ZTUEpI
        UkFKMDZZb202SGtoTDdTRG1KWWxwRW8Kz7K2vq0EEyo/+035IzS5Buw8JEgjxT34
        zT503wOGVYxbAFmNfoGs2v00+4csDdCtCGDcrIP/lsj0W2WaDu3vHA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-03T15:28:44Z"
  mac: ENC[AES256_GCM,data:b5gb5FfQfpNb6EsUA4RngS1rN7yGKvVVzACnsQjVt0+t0A0Nxzx2xbcMtnJDz+XTVtoNEPeyslc2Rsa8AYsEVyppz+37+jLSXCam2Gtdu0H6g7phpj9J85c2HkzJulAq2PFMv4LoIRj9LJvumUpZA3Pb4ZAYR3Anv+RKwCq81PE=,iv:tBeOw1CBrgdN2xvrVy5wtN1ARXi1ObzOqK1RbDSLwBY=,tag:C3XJIBzlVPaLQaU3xZL65A==,type:str]
  version: 3.13.3
