---
# yaml-language-server: $schema=https://github.com/fluxcd-community/flux2-schemas/blob/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sftpgo
  namespace: flux-system
spec:
  interval: 5m
  chartRef:
    kind: OCIRepository
    name: sftpgo
  targetNamespace: kube-apps
  releaseName: sftpgo
  values:
    initContainers:
      - name: init-db
        image: ghcr.io/home-operations/postgres-init:18.4.0@sha256:5086f94abc783f1147d7c2a32c01db00ab594820026e4f6a82ac2af3dbde7fc7
        envFrom:
          - secretRef:
              name: sftpgo-secrets
    image:
      # -- Image tag override for the default value (chart appVersion).
      tag: "v2.6.5-distroless-slim"
    envVars:
      - name: SFTPGO_DATA_PROVIDER__DRIVER
        value: postgresql
      - name: SFTPGO_DATA_PROVIDER__NAME
        valueFrom:
          secretKeyRef:
            name: sftpgo-secrets
            key: INIT_POSTGRES_DBNAME
      - name: SFTPGO_DATA_PROVIDER__HOST
        valueFrom:
          secretKeyRef:
            name: sftpgo-secrets
            key: INIT_POSTGRES_HOST
      - name: SFTPGO_DATA_PROVIDER__USERNAME
        valueFrom:
          secretKeyRef:
            name: sftpgo-secrets
            key: INIT_POSTGRES_USER
      - name: SFTPGO_DATA_PROVIDER__PASSWORD
        valueFrom:
          secretKeyRef:
            name: sftpgo-secrets
            key: INIT_POSTGRES_PASS
      - name: SFTPGO_DATA_PROVIDER__PORT
        value: "5432"
      - name: SFTPGO_DATA_PROVIDER__UPDATE_MODE
        value: '0'
      - name: SFTPGO_DATA_PROVIDER__CREATE_DEFAULT_ADMIN
        value: "true"
      - name: SFTPGO_DEFAULT_ADMIN_USERNAME
        valueFrom:
          secretKeyRef:
            name: sftpgo-secrets
            key: ADMIN_USER
      - name: SFTPGO_DEFAULT_ADMIN_PASSWORD
        valueFrom:
          secretKeyRef:
            name: sftpgo-secrets
            key: ADMIN_PASS
      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_ID
        valueFrom:
          secretKeyRef:
            name: sftpgo-secrets
            key: CLIENT_ID
      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CLIENT_SECRET
        valueFrom:
          secretKeyRef:
            name: sftpgo-secrets
            key: CLIENT_SECRET
      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__CONFIG_URL
        value: https://auth.${SECRET_DOMAIN}
      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__REDIRECT_BASE_URL
        value: https://ftp.${SECRET_DOMAIN}
      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__SCOPES
        value: openid,profile,email,sftpgo
      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__USERNAME_FIELD
        value: preferred_username
      - name: SFTPGO_HTTPD__BINDINGS__0__OIDC__ROLE_FIELD
        value: sftpgo_role
    httpd:
      # -- Enable HTTP service.
      enabled: true

    # -- Additional storage [volumes](https://kubernetes.io/docs/concepts/storage/volumes/).
    # See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
    volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sftpgo-data

    # -- Additional [volume mounts](https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/).
    # See the [API reference](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1) for details.
    volumeMounts:
      - mountPath: /data
        name: data

    services:
      public:
        # annotations: {}
        type: LoadBalancer
        loadBalancerIP: 192.168.1.120
        # loadBalancerSourceRanges: []
        ports:
          sftp: # Only SFTP will be exposed
            port: 22
            #     nodePort:
            # externalTrafficPolicy: Local
            # sessionAffinity:

    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 64Mi

    persistence:
      # -- Enable persistent storage for the /var/lib/sftpgo directory, saving state of the default sqlite db.
      enabled: true
      # -- Create the pvc desired specification.
      pvc:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 100Mi
        storageClassName: zfs-apps
      media:
        type: persistentVolumeClaim
        existingClaim: sftpgo-data

    gatewayApi:
      httpRoutes:
        ui:
          # -- Enable [HTTPRoute](https://gateway-api.sigs.k8s.io/api-types/httproute/) for the web UI.
          enabled: true

          # -- Hostnames for the UI HTTPRoute. Leave empty to match any hostname accepted by the parent Gateway.
          hostnames:
            - ftp.${SECRET_DOMAIN}

          # -- ParentRefs for the UI HTTPRoute. At least one entry is required for the route to be attached to a Gateway.
          parentRefs:
            - name: external
              namespace: network
              sectionName: https
