apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: openebs
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/storage-system/openebs/app
  prune: true
  wait: true
  dependsOn:
    - name: vsc
      namespace: storage-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: storage-system
