apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:dhKYoXoq3o4rJLw=,iv:ROu09urfn097eEvmOBO+Ehtwy+qOHgxNZhWUNVBeE+w=,tag:26SOKtcdwHjvqJYgjZlimw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZkx3cGZYdWVrY3QyUFFL
        TTQrcFJuRjVUbnNXL1FENkNtSy9pUWVrT0RRCjVFdHM0QVdNWHZTVit3dGU2RzRY
        VUlldDZLcTFRSjhLYW5XMmJscGtRWVEKLS0tIHM0MEhtOTJRUCtYcXBFZktQeVJy
        aUZmVUFvRDJqUEJzdSs3Vm1WbEVIRWsKJcEvPgs82pcBUnL//O8CnK9UkOWbD+95
        GjqBfNSYUbwSVO2pf3rR/T7PmtiAIKOSnRNCunDuTXOWSYlpHdkZTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T19:14:51Z"
  mac: ENC[AES256_GCM,data:OJpOkQAPY717Mm3CVc2YUsctrDAdy/7JhrIfeDnH84XLV98WhFVplexMMsy9Aiumg760bK8HxXfQ2Wqont6yC6glLN/zwM33tm7ANJaAFmYhRLmVCiW06wFKcH5NBHKfZc5Em3II57Bfj3C17ylpWs4T7BOdYUu5HUaVoiz4sRs=,iv:1Zs0OZuH4aGunhFghAYz3RJfNX30wDUanJ+kg8KtNGA=,tag:bPdyBwi3SSJQr6osuY1BvQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
