apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:dhKYoXoq3o4rJLw=,iv:ROu09urfn097eEvmOBO+Ehtwy+qOHgxNZhWUNVBeE+w=,tag:26SOKtcdwHjvqJYgjZlimw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqZkx3cGZYdWVrY3QyUFFL
        TTQrcFJuRjVUbnNXL1FENkNtSy9pUWVrT0RRCjVFdHM0QVdNWHZTVit3dGU2RzRY
        VUlldDZLcTFRSjhLYW5XMmJscGtRWVEKLS0tIHM0MEhtOTJRUCtYcXBFZktQeVJy
        aUZmVUFvRDJqUEJzdSs3Vm1WbEVIRWsKJcEvPgs82pcBUnL//O8CnK9UkOWbD+95
        GjqBfNSYUbwSVO2pf3rR/T7PmtiAIKOSnRNCunDuTXOWSYlpHdkZTA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-04T19:44:58Z"
  mac: ENC[AES256_GCM,data:1LSwmsbaDmX//xMS/bNN/iwmi/aj/vOaUNhMrGsOHoa/kBsGnxtbNOSBgK3m/iNeUP03IdouJERtbh0YGmQtIJ7W1mMWcLfpcysq04W4oHQ42hqic7rj+zJ7lCpRWiDtptzcTcjQeuZ+J7okXPL1N0Ybh9xePMR/6fIlMELkVGc=,iv:vJDfk97R1N4mNzC6lT9S/rjw23ZX6DXC3r62MvtI4B8=,tag:l1P6pw3Ti8+gvjyG+sHL7A==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
