apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: ceph-secret
    namespace: storage-system
stringData:
    userID: ENC[AES256_GCM,data:Il8M,iv:wtQ/uyZDJwPa/gIqTAATJXTEkNJbc7N5IwtnBdiLJak=,tag:Wy6iaH6kNAW+rGmwrOzFGw==,type:str]
    userKey: ENC[AES256_GCM,data:S6KnHWxjFpm2vvMeJau0IsxB3HOYWoVz585j8pe73R1NCIrtiUqZ8g==,iv:ClmMBDL0Akry4TUxqkjlHDLyzkvNycmrJBYDBFeHZWk=,tag:procZw9IgvZ0tarvPm0maQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGUVB0cVlTT0YxVVlXUnlh
            Vk16aWFOWmhlRkliWUlxN09zVDZBM1dTb2hZCmI4bjdraks5UWkvU1ROdWFJejZB
            MHlwTllHUnNFWGUvUkdmdWlWRFdYc1EKLS0tIG1Gc0hnZFV5YnpsM2NPendtbmcr
            eVJNWkh1SlZNSXdTaTFXUThqeDQ5WFUK/jHGN08Z4C7OG4/qeWovzpguipSHujut
            TcJtMU5KSSTJu5xnFuhX6pAGA2rOi4elZOszdzvQW0iQEDEODa0OZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-06T21:29:48Z"
    mac: ENC[AES256_GCM,data:jVGXyCi1CjXxkpI3CgRDYy7+nqLS/TlsaQNsUKOKOm10vC8NhQoKtsJ2M3S9zmTgY3PFKKPFe0hLTWiZGHzbiQ/Vg7Goncv9IDsZOkz1xptjkwwMVarSikJeaHiVOzYsVoXOyE8/u4VBOtKCGnl3qTpSj99EAAOZ42O4Kcc5Chw=,iv:t8d0SwfJ06JW7yPdN5iMVKZaOEe8BDNgLR3abXh7YbQ=,tag:u7rBs8HTiRAFfUSGZz/vMg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
