---
# yaml-language-server: $schema=https://raw.githubusercontent.com/cloudnative-pg/charts/refs/heads/main/charts/cluster/values.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster17
  namespace: db
spec:
  releaseName: cluster17
  chartRef:
    kind: OCIRepository
    name: cluster
  interval: 30m
  values:
    type: postgresql
    version:
      postgresql: "18"
    mode: recovery
    cluster:
      instances: 2
      initdb:
        dataChecksums: true
      imageName: ghcr.io/cloudnative-pg/postgresql:18.4-system-trixie@sha256:918ed523d6fa5572492afed43e1503bf6fba0b96f424f1a946ff7c4b67b152ce
      logLevel: warning
      resources:
        requests:
          cpu: 150m
          memory: 512Mi
        limits:
          memory: 2Gi
      storage:
        size: 10Gi
        storageClass: zfs-apps
      walStorage:
        enabled: true
        size: 2Gi
        storageClass: zfs-apps
      superuserSecret: cloudnative-pg-secret
      monitoring:
        enabled: true
      postgresql:
        parameters:
          max_connections: "100"
          shared_buffers: 256MB
    backups:
      enabled: true
      retentionPolicy: 7d
      provider: s3
      endpointURL: http://rustfs.storage-system.svc.cluster.local:9000
      secret:
        create: false
        name: s3-secret
      data:
        compression: bzip2
        encryption: ""
      wal:
        compression: bzip2
        maxParallel: 8
        encryption: ""
      s3:
        region: "eu-east"
        bucket: "cnpg"
        path: "/v2"
        accessKey: aws-access-key-id
        secretKey: aws-secret-access-key
      scheduledBackups:
        - name: cnpg-backup
          schedule: "0 0 */6 * * *"
          backupOwnerReference: self
    recovery:
      clusterName: cluster17
      endpointURL: http://rustfs.storage-system.svc.cluster.local:9000
      method: object_store
      provider: s3
      s3:
        region: "eu-east"
        bucket: "cnpg"
        path: "/v1"
        accessKey: aws-access-key-id
        secretKey: aws-secret-access-key
      secret:
        create: false
        name: s3-secret
