---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cluster17
  namespace: db
spec:
  releaseName: cluster17
  chartRef:
    kind: OCIRepository
    name: cluster
  interval: 30m
  valuesFrom:
    - kind: ConfigMap
      name: cluster17
