---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: frigate
  values:
    config: |
      mqtt:
        enabled: False
      cameras:
        # Define at least one camera
        back:
          ffmpeg:
            inputs:
              - path: rtsp://viewer:{FRIGATE_RTSP_PASSWORD}@10.0.10.10:554/cam/realmonitor?channel=1&subtype=2
                roles:
                  - detect
      detectors:
        # coral:
        #   type: edgetpu
        #   device: usb
        cpu1:
          type: cpu
    env:
      TZ: ${TIMEZONE}
    envFromSecrets:
      - frigate-secrets
    persistence:
      config:
        # -- Enables persistence for the config directory
        enabled: true
        existingClaim: frigate-config
        ephemeralWritableConfigYaml: true
      media:
        # -- Enables persistence for the media directory
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.170