---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bernd-schorgers/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: frigate
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/blakeblackshear/frigate
              tag: 0.17.1@sha256:1724960349dad0bd2ae8ec884171a6fd5755a4dc242a0e66cadbda9c0e85c99b
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: frigate-secrets
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /api/version
                    port: &port 5000
                  initialDelaySeconds: 0
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
              startup:
                enabled: false

    persistence:
      config:
        existingClaim: frigate-config
        globalMounts:
          - path: /config
      config-file:
        type: configMap
        name: frigate-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      media:
        type: persistentVolumeClaim
        accessMode: 'ReadWriteOnce'
        size: 10Gi
        globalMounts:
          - path: /media
      cache:
        type: emptyDir
        globalMounts:
          - path: /dev/shm
      
    service:
      main:
        controller: main
        ports:
          http:
            port: &port 5000
        type: ClusterIP
      lb:
        controller: main
        externalTrafficPolicy: Local
        forceRename: frigate-lb
        loadBalancerIP: 192.168.1.170
        ports:
          http:
            appProtocol: kubernetes.io/ws
            port: *port
            primary: true
          go2rtc:
            enabled: true
            port: 1984
          rtsp:
            enabled: true
            port: 8554
        primary: true
        type: LoadBalancer

    route:
      main:
        hostnames:
          - frigate.${SECRET_DOMAIN}
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port