---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: frigate
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: frigate
  values:
    image:
      repository: ghcr.io/blakeblackshear/frigate
      tag: 0.17.1
    env:
      TZ: ${TIMEZONE}
    envFromSecrets:
      - frigate-secrets
    persistence:
      config:
        # -- Enables persistence for the config directory
        enabled: true
        existingClaim: frigate-config
        ephemeralWritableConfigYaml: false
      media:
        # -- Enables persistence for the media directory
        enabled: true
        accessMode: ReadWriteOnce
        size: 10Gi
    service:
      type: LoadBalancer
      loadBalancerIP: 192.168.1.170