apiVersion: v1
kind: Secret
metadata:
  name: frigate-secrets
  namespace: home
stringData:
  FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:rAekVg==,iv:sYNxz1eTedTaXb5kiy8F7ER3+PLEZXvEAXVZXznxNQc=,tag:YJYGSu0G8BbvlqFSJOAg9w==,type:str]
sops:
  age:
    - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZFlyanpQcGJlMlBxUFdT
        TmFtZFU1UGxCemNUNEVidUJiaU1xVmhodWlZCmxKczZNSk5SLytpVmx1cXdRUGE0
        RnZ1c3c1RzdkS2FaN2pYTTdUTUV3QjQKLS0tIHBVaGsvYUNPNE1yMDBYSldmTG8r
        RUlQL1V5bFd2RjE2L0JpaXVLV3lzTkkKW78dvgcciJwFZItQzT6jdcGTG2Jk1KbF
        otbsPk0q/TY4BC4xsMuwKzMxOa4JFyl8gEq5zVdTWN4KCNBjHP/CSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-26T15:43:24Z"
  mac: ENC[AES256_GCM,data:EJ/B3c14bW6mWZL4spHkRIbR6qM8C6om5FxknTNOIdbqSzSOXgqrf/KicmJZtPXDZAx9j8wJfdMCdLFnbZw926Av+DQBblBwLRnjGShqnuNFCILDsf2i5TN8sqhCCIwq6pDCENnSDpWvDW35F6SezF6ZSftMAUXHvcDkAq2uoOM=,iv:+ckeukTb4HicmDp1N/3sj6mlJwvI6aSGLPsoa6kLbu4=,tag:ZU6yD8NvIgnrv2Qb7xF0NA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
