apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home
stringData:
    FRIGATE_RTSP_USER: ENC[AES256_GCM,data:XOWdyk3W,iv:B+TDAzIElfbwWV6k0ryIuV2LjhPi+GIF8HVFEylr+KQ=,tag:zn+bTfdUG7znk/Xhhtk0Bw==,type:str]
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:gjbZI0PEVvU=,iv:3p5toKsvjydtvR+XBxo1p0NIWh3Wp3QjO6vGKQfiaKA=,tag:kyBTw+uGYrxg03MDG2+0Yw==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:NkYuXSp8TUcVXVqjCHM=,iv:Gog/hEo20PKNexc2+2hXP8bQOecCb4pi51TSAQ6Ct58=,tag:JwzQu962NwTLugSnhPl98w==,type:str]
    FRIGATE_ONVIF_USERNAME: ENC[AES256_GCM,data:vRgTdAQ/,iv:7a+TLVsz24DfpyQRxVNXPdjwdt7Qvj+oF1k2Yi2GVG0=,tag:MfpCkuVrtcboTngKJ5L4Qw==,type:str]
    FRIGATE_ONVIF_PASSWORD: ENC[AES256_GCM,data:8/0U8yJYutY=,iv:0JZ59qfYSP4k8KEkIj+5rqyAzQSDSse9CxNZ7wEhShY=,tag:7SX9W9AzVdB60xC7WK9p6A==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZFlyanpQcGJlMlBxUFdT
            TmFtZFU1UGxCemNUNEVidUJiaU1xVmhodWlZCmxKczZNSk5SLytpVmx1cXdRUGE0
            RnZ1c3c1RzdkS2FaN2pYTTdUTUV3QjQKLS0tIHBVaGsvYUNPNE1yMDBYSldmTG8r
            RUlQL1V5bFd2RjE2L0JpaXVLV3lzTkkKW78dvgcciJwFZItQzT6jdcGTG2Jk1KbF
            otbsPk0q/TY4BC4xsMuwKzMxOa4JFyl8gEq5zVdTWN4KCNBjHP/CSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-28T20:48:22Z"
    mac: ENC[AES256_GCM,data:F05RCuXDQ7uLBLYx4heAdBVh7Mwhg+eUtaRb8GQ5lrZpW7j9+h9/Xcd8Y/C14aG4fablimknDcB9lqnC57ZeVFG39mgOmbc5uyN8xcerW2tSEk8eQ3m0ZZmFqMzUc8GgdwpvRp1Fk1ws0nHadUGEYom0E7DZdHH2HOM3/s9hXrU=,iv:HpmcQfg8px4I1oSeynuKm1MOdAMBeGYpLBvmO1xlDl8=,tag:pe6RrOB7p8n2GEf0Fk8U6A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
