apiVersion: v1
kind: Secret
metadata:
    name: frigate-secrets
    namespace: home
stringData:
    FRIGATE_RTSP_PASSWORD: ENC[AES256_GCM,data:rAekVg==,iv:sYNxz1eTedTaXb5kiy8F7ER3+PLEZXvEAXVZXznxNQc=,tag:YJYGSu0G8BbvlqFSJOAg9w==,type:str]
    FRIGATE_MQTT_PASSWORD: ENC[AES256_GCM,data:NkYuXSp8TUcVXVqjCHM=,iv:Gog/hEo20PKNexc2+2hXP8bQOecCb4pi51TSAQ6Ct58=,tag:JwzQu962NwTLugSnhPl98w==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZFlyanpQcGJlMlBxUFdT
            TmFtZFU1UGxCemNUNEVidUJiaU1xVmhodWlZCmxKczZNSk5SLytpVmx1cXdRUGE0
            RnZ1c3c1RzdkS2FaN2pYTTdUTUV3QjQKLS0tIHBVaGsvYUNPNE1yMDBYSldmTG8r
            RUlQL1V5bFd2RjE2L0JpaXVLV3lzTkkKW78dvgcciJwFZItQzT6jdcGTG2Jk1KbF
            otbsPk0q/TY4BC4xsMuwKzMxOa4JFyl8gEq5zVdTWN4KCNBjHP/CSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T18:25:59Z"
    mac: ENC[AES256_GCM,data:H0MMiQndYjVnMSCEz0/1v9Ask05iV9FbDWNjGC7q2q3LxhtYak3HJmm7hz7Of7HOWIpYalZpJ9a6Eu60kGJ+8dK2agZKSlGqnQEwwSoaox1SpzPCoK/cKXGP3cpT81ibukqRU7a6ug5dnJuQgNNSN2fVTO/LVkY/pzMifHaespo=,iv:bZ/SiF9Ad+TF6A7mPiXkD6liGwkF3TiL0wMAScacrf0=,tag:UVT/NH1m66OZNwTWuNirnw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
