---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bernd-schorgers/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nanomq
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: nanomq
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: emqx/nanomq
              tag: 0.24.13@sha256:acb6e6aea042090ce141815f29932ee563410794ad08a69fc74f725440cfda7b
            securityContext:
              runAsNonRoot: true
              runAsUser: 568
              runAsGroup: 568
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                memory: 512Mi
            env:
              NANOMQ_BROKER_URL: "nmq-tcp://0.0.0.0:1883"
              NANOMQ_TLS_ENABLE: "false"
              NANOMQ_WEBSOCKET_ENABLE: "false"
              NANOMQ_HTTP_SERVER_ENABLE: "false"
              NANOMQ_CONF_PATH: /config/nanomq.conf
            envFrom:
              - secretRef:
                  name: nanomq-secret
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            enabled: false
            port: 80
          mqtt:
            enabled: true
            port: 1883
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: nanomq-config
      tmp:
        type: emptyDir
        