apiVersion: v1
kind: Secret
metadata:
    name: nanomq-secret
stringData:
    NANOMQ_HTTP_SERVER_PASSWORD: ENC[AES256_GCM,data:9lbK3PtnZfgbk7lP2tU=,iv:uh/vBwnTBoT0DGm133fuCxWPD7IfHU8d7p3dzAehUVg=,tag:C9smNe895+KHgpziWpnXEg==,type:str]
    NANOMQ_HTTP_SERVER_USERNAME: ENC[AES256_GCM,data:3/mkdwE=,iv:li/iWw6inM0y40hXss8X2qdWxEEJBV3XMk4ofGzwcGk=,tag:27zp5/r+zvN73ch/oJoVPw==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBemtFbnRtKzlZWHNSSkVG
            RUNKWEtJZGdmZDI0RnRucDduRE5zQ2REUHlBClNIb1M2d240TEZSWlN6MXFmYzU1
            cHJkY0lKV0haeGMwU21ROS8wc2xSNUUKLS0tIFdvQVNkM1ZITWZtQnZjaEYyTGE3
            Nys2RTBCaE13c2JTMmZsZkRWSTBlVFEKXA4Ybi+da5BYDOXKhw02KAva4as2G/So
            E1FlGqVu7UL32tc1wYi0uE7mbMxzp7vd4QBat9STHspOYJqIxfKLZw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T17:53:08Z"
    mac: ENC[AES256_GCM,data:jnO0jU3JJlym+BLGJzEBkOROe0uZYCOdF6PSCrf03O/7QM2O+QoZ9JDhNrQfk/Y5d1RLEv3eCaufhfsE5CmzjvdlCDBrAkDSiw/QVKgMFqHFe/uTSfsquQ3w83BTe9/EDRbx7KiFAhwDYQ2Kl+5o46K6tiDezvBMYn5J3TKOT5w=,iv:2BZijGRAPBSOv6o+yGtyYoYU3QPRurPU0z+Dcw60pGQ=,tag:fX5RI5trqALC9+rMszfRUw==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
