---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bernd-schorgers/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: home-assistant
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: home-assistant
  values:
    controllers:
      home-assistant:
        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: OnRootMismatch
            runAsGroup: 568
            runAsUser: 568

        containers:
          app:
            image:
              repository: ghcr.io/home-operations/home-assistant
              tag: 2026.6.4@sha256:4d510e8826491e17049ede51d8c89afba28791e7bf7ba72ab8411e66e02255e6
            env:
              TZ: ${TIMEZONE}
            envFrom:
              - secretRef:
                  name: home-assistant-secrets

            resources:
              requests:
                cpu: 10m
                memory: 512Mi
              limits:
                memory: 1Gi
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop:
                  - ALL
              readOnlyRootFilesystem: true

    persistence:
      config:
        existingClaim: home-assistant-config
        advancedMounts:
          home-assistant:
            app:
              - path: /config
      hass-cache:
        accessMode: ReadWriteOnce
        size: 1Gi
        advancedMounts:
          home-assistant:
            app:
              - path: /config/.venv
                subPath: hass-venv
      tmpfs:
        type: emptyDir
        advancedMounts:
          home-assistant:
            app:
              - path: /tmp
                subPath: hass-tmp

    service:
      main:
        controller: home-assistant
        ports:
          http:
            port: &port 8123
        type: ClusterIP
      lb:
        controller: home-assistant
        externalTrafficPolicy: Local
        forceRename: home-assistant
        loadBalancerIP: 192.168.1.180
        ports:
          http:
            port: 8123
        primary: true
        type: LoadBalancer

    route:
      app:
        hostnames: ["hass.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: main
                port: *port
