apiVersion: v1
kind: Secret
metadata:
    name: home-assistant-secrets
    namespace: home
stringData:
    CAMERA_AUTH: ENC[AES256_GCM,data:49ji6g==,iv:AlhstPM8QOxHIfDfOcZQOjQa+wflZhLxypuJcActPm0=,tag:8H00BbgjVKWIgJ+OYhrMdw==,type:str]
    HASS_TOKEN: ENC[AES256_GCM,data:QFYIDQ==,iv:Tsdx+ecw73Qak7JQDceXYn5Iou9DAbY0JMcZ5fJuGTE=,tag:Kcg5UAThpoDbJ9XYzbrcSA==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDZFlyanpQcGJlMlBxUFdT
            TmFtZFU1UGxCemNUNEVidUJiaU1xVmhodWlZCmxKczZNSk5SLytpVmx1cXdRUGE0
            RnZ1c3c1RzdkS2FaN2pYTTdUTUV3QjQKLS0tIHBVaGsvYUNPNE1yMDBYSldmTG8r
            RUlQL1V5bFd2RjE2L0JpaXVLV3lzTkkKW78dvgcciJwFZItQzT6jdcGTG2Jk1KbF
            otbsPk0q/TY4BC4xsMuwKzMxOa4JFyl8gEq5zVdTWN4KCNBjHP/CSw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-26T16:05:55Z"
    mac: ENC[AES256_GCM,data:uinUyZgQT9/g0XyG+thNd7pX0rgC3Ef+4hpb+UkaIDOSGY1+oaq5euXawtnT7oj4eauU1BxDWLi1bwlv7bLBQjKjNJz4pK9Tx1yzHUo0DZafE6VdXBgreFQyUK5ZGB0gDbOXwvSXrBLGecnUQgS2ve8XqqhvjK0udnlAcFO3evQ=,iv:IrlJIazgWomSF0fenXT92LfW2ljexPrZYREdYgRp6gM=,tag:1DUC6fSh3ADctvavLek60A==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
