apiVersion: v1
kind: Secret
metadata:
  name: minecraft
  namespace: games
stringData:
  RCON_PASSWORD: ENC[AES256_GCM,data:4w/2ES/kVHc=,iv:FEaZceOyohrFSB1EzDqtdLT0J9gG+mKq7UlG257/D8Y=,tag:PATATjnSRQSFT41jwe7PCA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZDJNVVlISUZaQjZHQ2RO
        VmpRTjA5ZkprM3hBd2Mwcll3eVlqWERLMUFnCnVack83Tjd5a3Ixb1g1Vjg2Q2hP
        MlhwZUcvZmo2c0tpb0Zma3VNaGYzcUUKLS0tIHBkV3hNR3RNRlRieUx5VVFzeVFv
        Zi91WXFXa1FveURvK3pXNHkxdVRZZkEKl0ovqnIq9UuxXsw51vt+sKE8jjtLWRBZ
        EE4oN0e/m/91cflMj2ft25LraQxlLNUHOFRVK6c8z+7SspD9FDdC4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-09-21T10:13:53Z"
  mac: ENC[AES256_GCM,data:okvJUmMKQGbOoKMndifOctiuQve7A7wOeUj+TzWrva3R94de+1feyq4dcSKVGl9/Qe6ButB/z7g0DElpN3EiX48YAxhGZPmje/dl6IlSIXV7NYWoqyjD5L25kHJuIMq24m4bTb1Ra2HnNcH/s3XBEpu8oRy55KHM+7oejLZf8l8=,iv:Ahhduhl5KY3tO8pO/rZ6rHU+OuhBnrNkf9X/zYMqHPY=,tag:5HZn+1055wurXhpLQNpucw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
