---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: netdata
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: netdata
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  valuesFrom:
    - kind: Secret
      name: netdata-secret
      valuesKey: CLAIMING_TOKEN
      targetPath: child.claiming.token
    - kind: Secret
      name: netdata-secret
      valuesKey: CLAIMING_TOKEN
      targetPath: parent.claiming.token
    - kind: Secret
      name: netdata-secret
      valuesKey: ROOMS
      targetPath: child.claiming.rooms
    - kind: Secret
      name: netdata-secret
      valuesKey: ROOMS
      targetPath: parent.claiming.rooms
    
  values:
    image:
      tag: stable

    restarter:
      enabled: true

    child:
      claiming:
        enabled: true

    parent:
      claiming:
        enabled: true
      database:
        storageclass: zfs-apps
        volumesize: 5Gi
      alarms:
        storageclass: zfs-apps
        volumesize: 1Gi

    k8sState:
      persistence:
        storageclass: zfs-apps
        volumesize: 1Gi