apiVersion: v1
kind: Secret
metadata:
  name: netdata-secret
  namespace: default
stringData:
  CLAIMING_TOKEN: ENC[AES256_GCM,data:7LrK1P5D3H8iewmWmiq7Li9IHRef0DNn6jL1Cc7gPhQImZMmx6TxVC8ivGkLzcMOfzqbrmusLSmtq9yF5QOJqA5ONdaQzvunq5woZNBge1Q6qy8EVdRcNNh7MpTtnu+T0XKBlHKyKETtfuE/qGBm2BAR40+/LEOPE80QZVuc9yndLrfS/FuB,iv:yohu0EsSR6Hqp2ZzsDOftnvMDp3wC1tKT/4QXxL+7EY=,tag:0UvDXxha3BrC470n4dEqEQ==,type:str]
  ROOMS: ENC[AES256_GCM,data:SmgKchH2q9HDhxgVgDyJJ2Q9/OTSySfcbJf+j+lO7JzobFb7,iv:mMnRsOGH3thOqJt/2XrBLQLm2qT0FsC3+g1bvtMGTL4=,tag:CttksAbZ+LWlGuU0uDu8WA==,type:str]
sops:
  age:
    - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqeDBvSENtZzIzWnNSampD
        YnM2SWh3TzlvQTU0bXZWbDErWVo4aXhiSURnCmlFVi9jV2poMTYzK2xjOW5MRTZT
        Y0Y4UCtSd3pPd1pSYU1MOUhoeENwV28KLS0tIDNwckloRXIzUXAzVnk3djY5OGQr
        ZVg3alJqWTIxTms4eWdNZ0wzSHpkQWcKZArby4nqXOFV9WSINlymY5eLhpU8AAO5
        GhAQhU5bsSq0weXeghFtF3VMjjJJnkCvJ8D6mc4wNwYfrF3vgotaeQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-11T19:54:50Z"
  mac: ENC[AES256_GCM,data:sjWJv3O14Omkg9VqtD1VYtGI0DMYSHRghpG0HrQ7/XYtskz5bXE3Ftns8IUoClgMv12dUh3Mf3WSP1EkinGLbp/fcbsjAfOJuhDVLXbtO8gU6V3iYulRHTuutXTu5YV1VugCBjlpodTpyhCZ+T4Lx6CkGVmsSULtuzaP4xpdfp0=,iv:d5oM8OCHm+qGTrCL72B+EefyqZo7iYsoXVJq2hcf/ug=,tag:E/ilYNr2thWSVx06ycs3hw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.2
