apiVersion: v1
kind: Secret
metadata:
    name: robusta-secrets
stringData:
    signing_key: ENC[AES256_GCM,data:mgOs5C3lXQ4mJoYI0P7kADxtLVJtwDfLGZsMCiWaz4/kFaUf,iv:rAxW2XaZy2P3b36cjK+dJErkXfalVxHICwgSjUYaKso=,tag:sruEaNWV9virVEGW0Qxftw==,type:str]
    account_id: ENC[AES256_GCM,data:0nxAQhRSO76kNcOTCFGx59Z3zp1IRkDXrwh8px58KJ5ziMiE,iv:uCIPKt26sZ27II9VwQATS6btOX+4MPNKaqtvNPTskpo=,tag:NGBXJIzTb/rhswNTmNbpEg==,type:str]
    token: ENC[AES256_GCM,data:k0pIwgcxo/3s30wgMzXs/dmKSO+f8iwwgAdIsc266xz4FQWiNUHg/hecsLAhN/Qmv3YtvdBGi7pWavroz9DaMzgKbH1NrnO4nMzu9UYfPl9XBuZs2QdhilmTERbrcInXccKlo0MPivOkzyB/0/nWfLUzNyJjRAaJ4Jt9D2Pnm+kLNBkDVWMDZ17uR8wNAUu6/WKeg2LaRrcZWMcHlzFZ+9CC6bwUXjtGxKbreqRRjXSj2L+H4pXzb1Wzat9YDun4RFFDFEgO5Ew0GD1C2ZUf/s3VCSsv7hsWNxYj5cPbh+/DUEI0olMroxpjbMPRkeCgwaOZB7ya6XLdU0/4m5gCtIOsyAt58F4zE1qjvLsD4dc4D+duF6yxeB2ioZ1rq7WWn5iCYDgsrTKFgqRR66f32TbAsJX05l6cfnuc0hcilvlce+IUHgNmieprXvzFpojAE5ol+3TWeG/AtVQgOR7t/wqjXvsOjcO/TLBmzdUFdtYTfYDyjxZFb95tijqkARAjZCCd8gD5ntkT6OcWDjA5Z0Z2mI3zDg7MgsqKEFG2Td2d3grB4u/OUohcNW69dkwHqmBdn6lH3PgwEG+pRb5nF/AeJk/3Lo3szT/y13Xe2ODRzjRAnHwfT6QMoRQ6LoVocBEX0W5aIEHQr9T1qew7kjRzZuSyw4O9Q3+OwRZt3WDt20zjlIoaZeFypDZvF45AAxbOoljji2DfdaInrMfrOjTg6jOhiEGorgSHptGtrqo=,iv:7pFkt8ZLJYikJ9grhlEtEPW+FwWfLgVlrSn0dY3x2UU=,tag:pTztQJcL/ZwbxLr+99kPjg==,type:str]
    webhook: ENC[AES256_GCM,data:MHZjkwil1/S4/NhzYf1tFoDeW8GmZnS2Vbf1ruB22E3yc7jd+pA+lPSnaQy6S0W4ZnPULXLsv2hI2CxrvLLvNoJUH5LTW989KVeNQQW/C0/+jee6mL1hcJUf/FNkwMnmnLIuPaMR4gYXnm/+uY6ubOiRQuAHV73dwQ==,iv:IiKTlmMkYYFloDJAJ+SqD0qYl4vI55uomol+yFiJLec=,tag:msN6+DVhA8hgUD+WGV3Lvw==,type:str]
    bot_token: ENC[AES256_GCM,data:4nrkl9go/mRDivSlUcFSsSszJ08bcE4mA0G64h1sizgEMr6HnioviFr+BXohTw==,iv:Y7GpteAkHtvgAlAlONjlMl782cpfPfNzcuuiI09f7G0=,tag:HqGYLZszASfX5RbpnKiCuQ==,type:str]
    chat_id: ENC[AES256_GCM,data:uY2S6IXM5Ej3Xsc=,iv:mHgpxPz3bmmxLuoSiP12dfN40ltSs2uSCKJsNbwNfb8=,tag:QeWtOdpeJs7+zbaAtYozLg==,type:str]
    github_token: ENC[AES256_GCM,data:zzDDvbO2DDWEp8b6vesY7qoXratcolSf9yflIg1633y3bHJJuJYL8A==,iv:NKaco1WuhIe3uphR4nCYAcA5jsSbm7i7ITj8+eip22o=,tag:XrYBEqRv9RiEXw1Z/Wzw8Q==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQUNqbVJ3RGUxbnNFcCtL
            MWRmSGpDQ0ZDUmhhT2hlTGo5ODM3WEdqR1VJCk9VcXByUktBM1dGR3JnaG1KZ0pp
            RDVhL0t0S1hHa3Z2WHprMWRVODNhNDQKLS0tIFpXeXZTNkh1UWQxcmFmN1llS2Vv
            RytHdW1wZWxkSXhYMlVNbGlaR2oyVTAKtUjx8GVlQBdeueoMGZfHMdDfg79Hr8M9
            N/tFy1ar9KzScMkaOj9jgwHrFdotS7xyysiIYIqek8AJxz97BH+jgg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-05T21:05:48Z"
    mac: ENC[AES256_GCM,data:SOMZXXEYfXyOpNTXlZUPq3X9d/RO9LTasWNkHpNWm7d3ObXi2Ix/NVI/lBnybGF2Cmz2iXOgYz61gr6GU71c3Q2/hfboJhRLoKKD1y5EDcC80w6khYnUB21PEuSU0RayhMVamKpzVmr7NH8rwAny1EF/43Xbi4uk+VqtvvEFDQ0=,iv:8nUfhXSo5vP4qY35t6AjKXV0ycgnFKXdOy2p2OPE1N4=,tag:4wnktr9osUmC0+iNHyuzjg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
