---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${APP}-data
  namespace: ${NS}
spec:
  accessModes: 
    - ReadWriteOnce
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: ${APP}-pv
  resources:
    requests:
      storage: 24Ti
  
