---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: rustfs
spec:
  interval: 60m
  chartRef:
    kind: OCIRepository
    name: rustfs
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main :
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: rustfs/rustfs
              tag: 1.0.0-beta.3@sha256:378642b05b7dcb4849fb77ebe6aca4ced1c3f66e7e504247df95a5c9018d3358
            args: ["/data"]
            env:
              RUSTFS_ADDRESS: ":9000"
              RUSTFS_CONSOLE_ADDRESS: ":9001"
              RUSTFS_CONSOLE_ENABLE: "true"
              RUSTFS_BROWSER_REDIRECT_URL: "https://rustfs.${SECRET_DOMAIN}"
              RUSTFS_SERVER_DOMAINS: "$s3r.${SECRET_DOMAIN}"
              TZ: ${TIMEZONE}
              # RUSTFS_IDENTITY_OPENID_ENABLE: "true"
              # RUSTFS_IDENTITY_OPENID_CONFIG_URL: "https://auth.${SECRET_DOMAIN}/application/o/${GATUS_SUBDOMAIN}/"
              # RUSTFS_IDENTITY_OPENID_REDIRECT_URI: "https://${GATUS_SUBDOMAIN}.${SECRET_DOMAIN}/rustfs/admin/v3/oidc/callback/default"
              # RUSTFS_IDENTITY_OPENID_REDIRECT_URI_DYNAMIC: "off"
              # RUSTFS_IDENTITY_OPENID_SCOPES: "openid,profile,email"
              # RUSTFS_IDENTITY_OPENID_CLAIM_NAME: "groups"
              # RUSTFS_IDENTITY_OPENID_DISPLAY_NAME: "Authentik"
            envFrom:
              - secretRef:
                  name: "{{ .Release.Name }}-secret"
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /health
                    port: 9000
                  initialDelaySeconds: 30
                  periodSeconds: 30
                  timeoutSeconds: 10
                  failureThreshold: 6
              readiness: *probes
              startup:
                enabled: false
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 2Gi
            securityContext:
              runAsNonRoot: false
              runAsUser: 568
              runAsGroup: 568
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              # capabilities: { drop: ["ALL"] }
    service:
      console:
        controller: main # Point to the controller with the "main" identifier
        ports:
          http:
            port: 9001
      s3:
        controller: main # Point to the controller with the "main" identifier
        ports:
          s3:
            port: 9000
    route:
      console:
        hostnames: ["rustfs.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: 9001
      s3:
        hostnames: ["s3r.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
        rules:
          - backendRefs:
              - identifier: app
                port: 9000
    persistence:
      data:
        type: persistentVolumeClaim
        existingClaim: rustfs-data
        globalMounts:
          - path: /data
      logs:
        type: persistentVolumeClaim
        size: 100Mi
        accessMode: ReadWriteOnce
        globalMounts:
          - path: /logs