apiVersion: v1
kind: Secret
metadata:
    name: rustfs-secret
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:bven9Tc=,iv:K1yGfiv02ArWF0nfsglQlhl0HRb2pdlXVn9HWV/tEFs=,tag:ttTEWsO5y7tsudgQJer8FQ==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:SOaTUNyneo4wf6D+,iv:eCcyEfe6rkHPf5s/JQI9DKqX5boXBkGpW94STjB4sAk=,tag:/QB7Yl8Z3RYgPMxGPWLcKQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcXd3ZDZMM3Q0elBCaVZw
            VjR0S0tJa2ZMcWdrVDRCbWVoeGNQSkRRYzFVCkxtRkFQS2JQRFUrVmJlRHRRcS92
            SU5vRkN6eSs2bitzMXBVS3F3cFJ0eGsKLS0tIElpN084SGpjN1pZTEdVZ3BNZEhZ
            SGpSdFZnc1lRTk1rd042UzZ0c1VLQ0kKQnaIe3uAD6lvV1hpZroDhK//1LgDpDCv
            kzTsY+WedCM0AvWq6FpgwGRBqBCzmrUxjCHe/6efKFLOc4+NXmIYpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T09:08:24Z"
    mac: ENC[AES256_GCM,data:VpcRFicVO8PIuVczXzXYDnmJnWhi9GneCh9vsLoDpahnTs0xgSbeunLIJB+FtGpEwZAWxn6L4XrkqE/JiK8lx8/CVFUCO+D6bqWftkEA5Eb4nrvzOU+KIgg4/T1WYWh+0GjJr373k4LTGnSy+6uwPCWUE2L1zgX7yc0MH0tWhMQ=,iv:p5AwWxNB8WPAaYckpMXXTlWn9ujfywaYATbcTquvcIE=,tag:COkvn2oMVMtKK/CSQzq/ug==,type:str]
    version: 3.13.1
