apiVersion: v1
kind: Secret
metadata:
    name: rustfs-secret
stringData:
    RUSTFS_ROOT_USER: ENC[AES256_GCM,data:wZCFQXE=,iv:40LgQ4INecyPySX2Rvvvlr08lYy0jqFbGm234TxCN2E=,tag:+jW4+YsZMUTvotnm3DpFKA==,type:str]
    RUSTFS_ROOT_PASSWORD: ENC[AES256_GCM,data:ruRXVe9J9tsQE08h,iv:mHFL+0K6cSJQKcb3lBrmqatalHeaUVRa2jzGA6quwyY=,tag:wAnRRfKY8iam7Mi0HoQ4pg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcXd3ZDZMM3Q0elBCaVZw
            VjR0S0tJa2ZMcWdrVDRCbWVoeGNQSkRRYzFVCkxtRkFQS2JQRFUrVmJlRHRRcS92
            SU5vRkN6eSs2bitzMXBVS3F3cFJ0eGsKLS0tIElpN084SGpjN1pZTEdVZ3BNZEhZ
            SGpSdFZnc1lRTk1rd042UzZ0c1VLQ0kKQnaIe3uAD6lvV1hpZroDhK//1LgDpDCv
            kzTsY+WedCM0AvWq6FpgwGRBqBCzmrUxjCHe/6efKFLOc4+NXmIYpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T09:16:24Z"
    mac: ENC[AES256_GCM,data:48IX2pqH5Zg8ZKyjftmuilgsVj/CBr3MsAhgT50jkvesi/uHWxCZhF9/vgWKixlunDRgCj/WSsK63lyGnoH9luuCIx6cl48MNhZINS/nJ9JAdOr4qtJ79zCDqDrY2nM/lOwWShgEXkch1+Mihdf9riClw7d+dNbmHh7bsZsuyEY=,iv:G24ggqjDUkI0wC8JfOj4Auw4F4T5Qy0AmUJ0f5EljW4=,tag:jt0EqhEB6Wjdm/xE24wsPw==,type:str]
    version: 3.13.1
