apiVersion: v1
kind: Secret
metadata:
    name: rustfs-secret
stringData:
    RUSTFS_ACCESS_KEY: ENC[AES256_GCM,data:qmwuPg==,iv:vbVcB4zIdM7a5RcTjochH3ekMlWHd96O129P5UTkzHI=,tag:oIuyelW9BJ2Te+Gtm+h5qg==,type:str]
    RUSTFS_SECRET_KEY: ENC[AES256_GCM,data:k3aL9A==,iv:MgMEX6Utnsf+Y5ERCGYQgyHlbk0ILQH+wOANrVUxhKE=,tag:k9dyPnyLdls+GPLf0u3DSg==,type:str]
    #ENC[AES256_GCM,data:7PZkEniUipYh5RRAjJ5gBNHfgj2KK/sQCiYCkSH64dqOexcIUzwSEkbr7sC7+o3lBpanrHZ3xRrsKnrlbra6uI8nVQ==,iv:F7f1kImdj3cdEs547slB2+zu6lcvIV4YWM459NjmWEQ=,tag:yymOSYvk8zgPnyBq5q0uOg==,type:comment]
    #ENC[AES256_GCM,data:xyPWzabmvSqAsEmgw3HFy4kKgbG9rXjsHwKOrKRtwkudXOC85S0c7ulr95XLaPvRGQeOilFb4LyQdSo9ya0N3OfagJxiLb5HLWQN,iv:a9LXqTADVrH2pDreh8f0UxAgoKvC/DBCh5BTcTK2OaM=,tag:vLHSfX/9pcwcuwjULXI/uQ==,type:comment]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcXd3ZDZMM3Q0elBCaVZw
            VjR0S0tJa2ZMcWdrVDRCbWVoeGNQSkRRYzFVCkxtRkFQS2JQRFUrVmJlRHRRcS92
            SU5vRkN6eSs2bitzMXBVS3F3cFJ0eGsKLS0tIElpN084SGpjN1pZTEdVZ3BNZEhZ
            SGpSdFZnc1lRTk1rd042UzZ0c1VLQ0kKQnaIe3uAD6lvV1hpZroDhK//1LgDpDCv
            kzTsY+WedCM0AvWq6FpgwGRBqBCzmrUxjCHe/6efKFLOc4+NXmIYpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T10:38:08Z"
    mac: ENC[AES256_GCM,data:DLX51AnqzIkaSuI3oERnSCnrSpAlhrHj1AU/aattAwTmgSwOg0qHmb4HeCPKkMdR+xpBe+CiwugBQX+Qizg5DFkClLrYGSwcOv20X7K3ZMXFHpqvDZz6VNKJnm8eTDDB5sXIk7T+vE3MjIS+lqC89n+/J6yruu7YT4tzFr7Itf8=,iv:ht9feDuWZFetVxZ0d9LddykQdrKUetMnxOEVmFsLImI=,tag:iP+LtWNODYr5+1zMSL2nNQ==,type:str]
    version: 3.13.1
