---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vsc
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/storage-system/vsc/app
  prune: true
  wait: true
  retryInterval: 5s
  dependsOn:
    - name: snapshot-controller
      namespace: storage-system
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: storage-system
