apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: democratic-csi-secret
    namespace: storage-system
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:LzoUiBlNROmjQc+UiFAQemSkHQCVwpFabY53cF1xjk4f3duCBTCwTF3rzxDy+o/LCnOZgzeZeDfyKu17psGyXF6SrKy7kYkgQg4Wof4utGDrNPJ8mIN8Kx49/hA8IGpBbyzS9Qj7BNkbS84IRBRW1+feCLyNxxkBRR6F8Hy202DcCOUhE0Cwemk/mnLY8UejFW1iv3ZEiwn+XxXh7rfRIOKLGxYI2ntSn7sH2mvs+/8qEiOn0ZAHnD6KBOar4gMxvSahc2kZOUM6mFqfNR94hyRFf8MLcB8+Da9H6PejHw3cD4GO5qGVX65TP5JB3OeYxXJPRL09loV7We1QHWFUa6ovAdvjGNFT0RFiDIp16PEJGxwDUloKQelgz48bBlONypn0PT6cu2Fcb4EuXaqFzNVPxiOQyRyY4FI9DPNa5gYS6+1KjGJXUozj/QZbjQh0NJ3incbihh4Qt3Io6t+H83hP43QIHznas83C4rUf5MatJwn0ITODPrAVNN2dFkDZmwHNMDKa03OIb4qdyTN6ezv7DcKey4UpWm69uttpzm3ssP2oBLT4ckssSZsDG3Jag/EeFDggMpipE4zBuOV1YbM6+RrRE4YsmOLQOyPggLuNpcjVAWDmXkJSuBuyJ5+UNn5PdTcGqyy2u+JcrFLo7MmGKPFofc05o/ioNd6fsZhYH1gk/pnZsiA1ZFPdOR+zAb0VUv51MMm8vjO2pf2VnfAgsK4K0FyjeCyfR0lilqHHBKaP0M3fSE9lNlUy8F8ROfPj2CTP6fMtnDx3M/GNcU1gcWH4ZhldPkjmE5DoVyqC2dQiFWPTS8YZButq6tzDdItNtyZLVmaM4Se1hxX4UMMnm8An8uXZz16XXzAZndcprRKOWdmFXbnYb3hMpkML68SNgZTWXK9SPXflFQZ95biUFccw9ZlYmpRch3Tft3hP84Yr7HPFdOZPKMtHtBvY8NJA0fQkE30Z/7yyMLhSGdn4hncbMS2BUqehRa/5rOcN0Qlx7UpLeoaWrGuiwtgLFneJBgxIxOHbMYjtRODq8HpM+ZGDsxDE8lqXSnk2U68BA0dcDSaLwT0QDwZmtgKVJxbb0OP24mNeslZprymsY6HELNjdwfAGVHewq3V2fUvwPgUW+vOiW54kSfC0vU/WemQvGr0ZJc7Ec3xTEbttL2LPuXtagbx6zfn1WovxJI/iCSQVVcNUZ+iMsXxNJ1R8/MAYOsB0TVko/fSZ4uWxXGlXdhwZRolRXRO+GJjTFzqtm/RLpSjvvbCpB3tqt11+SEylYJdyrAyJkyTxjIVsqvWe1iNeOxKVt5fuE1q3ZAJajAWNsNjkD1v5CZlMn2XoJQqZhj1XSV+tMh5BZYHvcta5p8+FN2JmsBST8TfEv2vd239teNjT0dHy16NFBOM=,iv:hpPt6BYkdr3OTHIO4/DaYxhoN0JCC1MlfDW2R3cbaS0=,tag:A47EfYplnn6fwhl1uCopcw==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcGRtZVNUZS9OVzVoUDYz
            MGhpOUtTRnY3ZVFyaXFnS21BT1k0Q09oU0JRCjllbm9FT2lJQ0lPUFN5dEc0YlJm
            ZWpsSTVPR3Yxc3FyMURtQUZNRFZ4Y1UKLS0tIDdid0pmQjBteU00ZzY3Ym9xajgv
            bWlWOFVEMTNSN0VEd2ZmQjJ1dmpBOVUKF+MUs4dJNYMDNsB4t/5wdkWMQEz4pPmy
            slcG7NPo94S2YsPdFGK1pKGXr7mM/kN48E2106X5Lo92TwBdfP8xAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T21:40:44Z"
    mac: ENC[AES256_GCM,data:sqV6Z5lA/vTHPxzA3sSufhvh4XKJHP9wM1tzLkevQ8iCoDwSwmgIPxcjCsf4/djUCVBhpPGBsBIzfGgvg4YtKhGese3Ukc4EEWCI6gPvbjlid6gj2QZEzZy3aO1wXEx66xbuTcKklj66+K+r+gOylRt26SrRWXV1uqaaK+w+K+s=,iv:+tId7aj2qrbYus8+1mQqKT3jb3c7J0b/H583V5C58mA=,tag:by9PEKJsSu4wEG78fR7p/g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
