apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: democratic-csi-secret
    namespace: storage-system
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:k3mjAy6muGt5lvL+l4GJF8vnW/t5UoTx9sNnws+8UYA7uH0bf8EX+SSRoMcN/cwattvhyOg6eV8AB+KNILAAtp/L8c19yBtpfYGsAV+z2gOj39Sj2yDUWEGnqObmEN16sTkmPGmvUX1a6t3p7wx/JuTNLmvkw366cfOJV6s3u4oLqY55s0WqUhO7Wl8P08I/I70q4jB7xO5vReWrKm83iXGTjACtXxFMtxtQI3VMbLT9E78wjxnqeL8CccIjzec6Oz5MJ4SOFr0rEOb8Bc+MCxKpO8+8eOPrkDEaUmJYUJ9wOx3O1Pyi1tV39i2c8E44gxPpQnbRxX1T+ynOy+Uqzxrw0dN+RSLHy2uZ2Rxhk0NuVp71dDCxjMSedK6YQfIdOLdRxxxgyii7EfaKYzo8Arqh6GuiNyXJ12wQ4g4/MM2wAmDNclSfEPo6pAy/cH0DvF19uE/PjFEp2vsa/TGAGp5Qi4G4M7nW0u7cFecFynzVSq2oL1w85bPqkJaTgQTa/80qpOXhiffPX8Lr2fJ+dkbtdl6hEApywNWKKgVi9Y3RVZarc8eO2ZxNrzyhMIgDRzZqFGQO0+18AzVbgCEEMhT8QJ87EB9OqrIQNkYnxK5B/Gz3jskqsBhWLpiktZ4fYTEysStW7G4L61r+h4MsDZ+guf5Gq9LVZ2poqt6KXXcbEz4AQN/JYNn4lXBFEnS8Xp7xsfANYJSX6/y76K6RxNtBWJFp5T9DvbssQm/wDB2x3nSscD/5/FaQG+hmWVUSp4FYPI6Yn0g91ndz9aGirPEnOmr44JxJf6o+d+Q8aH2vUwMt/7IupIBJRCCp81iw6yQD7SMYsoZvw61sA+kb9epoar1gZZvzFlXvGexEi/Jd/QOuF4WG/AN3bi6gHVoLtQRDwH+cIsxRcNNQSOdBhFIkWrnK+T7puetS154ZyZfAYB8gga7YluuaAq1HUzsj8q8ta6gE9y+dOLHy/Wcg9kIGpKhbUd/Knk3YNFLkw6/Jf9gQiGxe4LIL5rtv4mFzCIbPt/MT15oc2gkJI1dkXOHkYd3IUr2oQcX+wZiO2IOXfij2hSmT/jnq2RLLpFZbkwJcVHPclMMH4hurZbv5SODl1ym1Fsh5KiavlbJvuQ+t8DWdI8Q5eBtq/lrFVmdqeaj+DCxCYQIsx6YiMkYM0Oz3by8tYYop7EqNyAG8F23E0oNU4E7kgjX931dS4tVoR9WwTgWzPQQ6ZKGsUBGIv5WmGY0UauD48CLW9Nh3jusKCBBzVR5zDl7x+J3Iucf8SXbPUlOjIgQs/wrpHAR0E3bnrYQzkQuYIdpn31b8LdWpbhTsuBEujwqQyiw1mysUIhGLNBg+wXFginqxA9p4Iy2q,iv:sMoyuDxChS5tWRsARJupBDIr5u5fJR4iUuYqoRGrzFc=,tag:cTp8HN+bJaIxGMHYTghp8w==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcGRtZVNUZS9OVzVoUDYz
            MGhpOUtTRnY3ZVFyaXFnS21BT1k0Q09oU0JRCjllbm9FT2lJQ0lPUFN5dEc0YlJm
            ZWpsSTVPR3Yxc3FyMURtQUZNRFZ4Y1UKLS0tIDdid0pmQjBteU00ZzY3Ym9xajgv
            bWlWOFVEMTNSN0VEd2ZmQjJ1dmpBOVUKF+MUs4dJNYMDNsB4t/5wdkWMQEz4pPmy
            slcG7NPo94S2YsPdFGK1pKGXr7mM/kN48E2106X5Lo92TwBdfP8xAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T21:26:10Z"
    mac: ENC[AES256_GCM,data:KWDS1ADau1z3zzcBH3P0d8MPvTVOXd/MwMI3NyvOTaTRvDjqFYSfkRSm/XkZxszzdmzfEwHg7CrWMza547zyNfc1B9CGjSduQD0nDsW/Wz6RG1n+hGD4X25ZyUXL8cX9SK87ORlMfc5v2yd7MUi+3Se/gMzi+ZScbEmfxgzhGcQ=,iv:Yy2Qno2qsSslhiqSKjWLqvPtPeGRauvpFEMNQpb61Rg=,tag:YcpXxn6LHmxmrV9MS5Z5fQ==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
