apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: democratic-csi-secret
    namespace: storage-system
stringData:
    driver-config-file.yaml: ENC[AES256_GCM,data:tAq+moWftGBzuvN45TyGQoJrVQfD/2phK5XdBoJ4GC2Hl+Cs1YjmFr2r7zhFFcQno21rGh/2sfSIsr64mRRvi4o/8Gb/YbKQZkxoAWQBdV13wu7cDeJR/DbIzX4rHtyMsEWn/72IxVAWc4uNoXie3UDIAXD5IQEkJD8NgdZ6zRm6+ANt/pESwdZa11DLBAiuybkYACykDYe6nKKRincXknhuQMzaYH6i9PtLJrzoFdk1x+tRH9WKFOWeYl9zRbC9q3M04YEq4QqleRJBwu+aiH6x8JrQaEisb5eqh13fyK1easw/84R4wjIXhv8RPGMUjXimFN70X+m5kx73cgO8Vp8MYpD3Wp3EUxEmDJ3MsV41O1p2LcXAT2majckyYGDYvI8vtGGVD+KV4sY1PQT6YNUGNmPsu3HkwuDbAdtIwO3c2ZO8/q77Ota/sMiWVaplDVdCgiD66Yw3lNsLlLQnnsBc9HGPgCn4FoNxGv47bvTDQ3oGWHD9YdXOOp+6qq+vPeIwJO55AzFLwUPhbmX4/Eo2yY4ITCvHBGO5Z0NBnNteM9MQ1DI+qCocR5FBf9+ATsYlnfxf8HGPcrrU2BxV0dg30lxekeNjAaf1Jzo4bPLqm2SjmLLPl0jDj1XW2wqVEuGplU/KuVpl6vkHrX6cD6CKVL2oj78Lfg0us7FpQym+OGT138kBmd6B8bDom0Nd+vU5oC3rc1sDt3nzmYQInnODyaCk+RFeYw18Qbkg3zDaX4IVaIYMjTx7jOhJT3hgGnXf3Uu7hzdF/LuNP/qD75+TdG0XWKsAnTHzeIpUGwFbFim5sHhUF9zAMolv97/fYdkTazGfVnGmaLNAadidnUKFTT/0EguzLQb1WRmmdxu7Vn/ian0AS5jBvbvsMILYtQQLQtJABpKM5L48AmrGCEMB4TF2ZJieJ6/6ply+oLGLl/pkRe2UIOxaDixajiRhX34BSlN2Gi7yBB7zG6JzgcUAJh7yllSaBhrVYz4sfQLgOdCMVGb/X1PwKsqQlhGQIA5yQPjxueDKTKjvyHNcLo+6TiIL1ZEmTTt7g1BUiV2T6w9Rt81JLAb9LirDYkRFKlY+MOcmMOIaKpEsm0mYfMZp/3P+edTdyKsHG0qQ4h7qzzFZk8eJ9yZ3BGlab/oWZ0GOn2gGnignuhuvezspOip1ds3MQHwGKHWMJydEWyohu2Kt6CPsCRviScn2PDF/b33z3MYzk+pMugCcWjUIiFCaIwTc8D3GwisqQCWYXdzdXu3BF9APqyQwOFZor0y7+/CSo0mgP9Dypsr90pj3BU2PcxEt6tJQkCO9S17SS2m0VnGw+C60m5QNwJLWBs7Hw9rSQlnziZEKbRayMWPjuT/r6PeGsMuEC9kZSSGPB3dhEMwC4M5vHbksq47EKaGae0EeZ7ZR3a+I87cKRI9foFVmN3Ww/eS803/jNsN3H59lQBPKEK2x/xVLdCAf2cVCezy8HX3ls3Vs9loR5MVy3GEYRWBiEWySluw8GYgN8MRQQBD3tdZyTkzaFbrg4Dt5kKDEePCa95Ekn2P50daAL9qAOA6eU76OdGm3eI8+BrZ+monQKv8m8MupMy5blUILgYo6D8dP9LxbasSkmnSdSYR2UfPjAShlAH2CtHCgS8U+Gr0Nvznt,iv:YVzfy+ZdA7EL/4xNQqLsdGHtZCtj75PyQ0H6kDeqD8I=,tag:Nez5vopygOjT5YcuSmv5YQ==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcGRtZVNUZS9OVzVoUDYz
            MGhpOUtTRnY3ZVFyaXFnS21BT1k0Q09oU0JRCjllbm9FT2lJQ0lPUFN5dEc0YlJm
            ZWpsSTVPR3Yxc3FyMURtQUZNRFZ4Y1UKLS0tIDdid0pmQjBteU00ZzY3Ym9xajgv
            bWlWOFVEMTNSN0VEd2ZmQjJ1dmpBOVUKF+MUs4dJNYMDNsB4t/5wdkWMQEz4pPmy
            slcG7NPo94S2YsPdFGK1pKGXr7mM/kN48E2106X5Lo92TwBdfP8xAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-01T21:46:11Z"
    mac: ENC[AES256_GCM,data:qMQ+6cgpvpq6aXzOqphcsPtyiZgbv5qeRt+Pj7zzEQYp1pkjN/m3vzD6chdQh7qSvHVGHI8aAOchuvYfxCTkfn/gn0E3ZWIgk6OBT3cNeSviAiOlPCX7V+hNa15sKbCznxdmBbu4BSvvt1luyQn0zdX+Xm8KBZP759Izk8Dgt6o=,iv:OjkmDgcbh8tJlmD3W3vZGQasPBMxZwxbLGKBuU8eFPk=,tag:xPZ0v+vdM8zHiJtbWnvdTA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
