# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: longhorn
  values:
    persistence:
      # -- Setting that allows you to specify the default Longhorn StorageClass.
      defaultClass: false
      defaultMkfsParams: "-m0 -Ediscard"
      # -- Replica count of the default Longhorn StorageClass.
      defaultClassReplicaCount: 1
      # -- Setting that allows you to enable automatic snapshot removal during filesystem trim for a Longhorn StorageClass. (Options: "ignored", "enabled", "disabled")
      unmapMarkSnapChainRemoved: ignored
      # -- Setting that allows you to specify the data engine version for the default Longhorn StorageClass. (Options: "v1", "v2")
      dataEngine: v1
    longhornUI:
      # -- Replica count for Longhorn UI.
      replicas: 1
    httproute:
      # -- Setting that allows Longhorn to generate HTTPRoute records for the Longhorn UI service using Gateway API.
      enabled: true
      # -- Gateway references for HTTPRoute. Specify which Gateway(s) should handle this route.
      parentRefs:
        - name: internal
          namespace: network
          sectionName: https
      hostnames: [longhorn.seganet.org]