---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopiur
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/storage-system/kopiur/app
  dependsOn:
    - name: rustfs
      namespace: storage-system
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: storage-system
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kopiur-repository
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/storage-system/kopiur/repository
  dependsOn:
    - name: kopiur
      namespace: storage-system
  postBuild:
    substituteFrom:
      - name: cluster-secrets
        kind: Secret
      - name: cluster-config
        kind: ConfigMap
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  targetNamespace: storage-system
  wait: false
