# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: flux-webhook-token
stringData:
  token: ENC[AES256_GCM,data:OQFPokNmS90OYon4STreN9+Qszx2Sv2t0zBb4BuzN+E=,iv:Ub4hAX3Siut9sI1lrN0yymg7f4OfuRngc/d5VtpSwQc=,tag:C17yLYReW0m1sT15vcm5VQ==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNXhvOUF0SzVYdThFdnBP
        K1RpVE83Vm5LNzBhNUxlQmdTRE42T1U0K2xjClZVNmdiN1hWZVJNbHBob0JHWkxw
        cU8xRDNaZWNkQ1hINWxkZVFybS9NclUKLS0tIEJMOHM0YjNOY3VCU0xjY3ZnZ3Vz
        Vjl6QU82dk52Q1lFL2RTTXQvNllUem8KtljRMZWHCoUA2JO/sru4dLUXKKCnVIy9
        yPuYe2D9gC5m0R+hczDzzE8IEtaYjSsbZt4W2feY0i4GV7UtliO4EA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-08-13T11:03:51Z"
  mac: ENC[AES256_GCM,data:ym/kzSS6R7Dp/rWXpHDbnaEH02uuvhzgN4IlR7K/mr/2FUcztctosMUk4KqndKqLb13kg0SyG7vUXFdtWVKPO+nYmN91sOma/QppWYU9ME37U5g/LUpSvy9IIgkcmJhGGs3qnsN24zCpdQ2MGIeUSKnNnUOXJDvVIT+SZ7anJBk=,iv:Ubk7EDflbBOZklaccRfdgkxaEyj6eyUG3gljCpzFgbI=,tag:bEjs4aoKPD1rLZjoFkSMPQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
