apiVersion: v1
kind: Secret
metadata:
  name: cnpg-secret
stringData:
  username: ENC[AES256_GCM,data:1r+bd3hzKAA=,iv:UHTQFeXfbVSO6jtaLaMSlfldfMCobYSmXikIoJjamHQ=,tag:H5jTErT3MibD0bPiB9vryg==,type:str]
  password: ENC[AES256_GCM,data:9nhh9g==,iv:dQMghyt3DrpIw4hqSD4ixWUNapdkNP0IGSXFZgLaKwQ=,tag:LbLrrRCjQIiYMwUIUBZRxw==,type:str]
  ACCESS_KEY_ID: ENC[AES256_GCM,data:k66ThWXci39zKeQhYCNKw0DnFTk=,iv:2AyuLuwLnhcRNKaG9IOngbtY3lByCYxGsH7RirhbiSE=,tag:ilP8GR8bQVAtBacmMlwx2w==,type:str]
  SECRET_ACCESS_KEY: ENC[AES256_GCM,data:2KB3tQYVVKkerEPEZAY2A5eYlabVod9vNTBlrHWp9hJdDyqVYlGbLw==,iv:dzNGh4YKDTiBnJscqMn8onmx4PGE49qjGBnWSCNDmdw=,tag:VHrGHut3HNRbBFwrORKu5A==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkTVpFTUZtTk1JUVFXSStr
        YzE5ODNSZHhGc3RjcEJUYTZxL2lpaUkzams4CkRxK0dJS0FFNG1HOG5mWktWemNk
        aVc3ZmMwWHlIaHUwL1NTN2lZd3dPV2sKLS0tIGFOU01udXN3Z2dsVk1UU0FnbkE2
        ak4wVGxQSVRtTFRyMDFKQTRYMGVvYkkK8+Z3btE51I0PAA9hz4pOLkOgOPH+oLaZ
        9jBvdFra08Uv3B+Z4JVuIyVftTGfg1miWo72kNzj9dpPB9/T539NKQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T17:23:44Z"
  mac: ENC[AES256_GCM,data:XdpI+0OJZnQAPFOo5BAFe3i+nMNlHNBDytSB3Msc+xv7daNREBfoy8qxbIFhYGTXk30PYLVctYT7o2SNL/647VIGrvIzsXuqIGCw6By3K5souW5/US/9o5D7gvZBGweQJwcVzhulMCJgXWFlAZKocEXAagTrm0qzL6ni+oh2Kq4=,iv:DEDgEz+PHBbEft5c9ya7gwmp+8JFqSJbB4TFMxfgTj0=,tag:tmtSb6TiBjaNZ9Kv1QWhYQ==,type:str]
  version: 3.13.2
