apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
stringData:
  ACCESS_KEY_ID: ENC[AES256_GCM,data:JDAM8Dp1OlSpLirHE0pzfLrOsic=,iv:qknDXOhwuBpiqvXTvOVfYtHo370ryoJ206X509UJCIk=,tag:1Mw6Czfhj0L0qV1CUkwTcg==,type:str]
  ACCESS_SECRET_KEY: ENC[AES256_GCM,data:BRsRzTvH+O7/i3euC8LZicTAKdTXf8TppjazhP9CZl5nnx4D4EJsFA==,iv:oMESblHxoKYEBsxwzWSi637KWa/BP3nHvUyvphiLQS0=,tag:eRZ4guTQSQxJIYtapMdGLA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6Kzd6aThxeWlxY2pFQ3J2
        NVc4VGdWcUpNWkNKRXAxWWxVbkE2TE9KNWpJCm5meWFFQnV5RHhDajNjemZLaFBP
        UDY3TnQ2N2trcHdGTHhSMGk3N3BMQU0KLS0tIGxNTlBxbTlDMWdvMkNDQ2hZcTNL
        Z0I4SFNYUDZjT281RVNNQUZHdU1CWG8KwJ1yRoWGjPGMQZxIlxDnNxnHD/m0o2xk
        U8odRhH6xV/2UBdD7zfilmxrAsMeF9oLzgtkbkXTUwPDbt3ZfueCUA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T22:33:50Z"
  mac: ENC[AES256_GCM,data:E4ziW/ANblHn/4amPRLf50uy4WZfyXQPDZ4ukiI4Jk0Cko5Eff/XD5BoXjLkfqV3PcSkW0YM2ZZSUs15b/L3cp6CY6IzHzlrs3SJT6RbRXe7Umt9QAxL7Z+aKDMbtjtGOorKGonT8Ly0S2/d1hwuR2j9Q4mq11payHPB3wE2YEM=,iv:M4HvsfvxzAvn0/l5oUcfEtaZf97nS+lqRxCaqlyDLMk=,tag:4Ztqo3JzLMAoZKtU7sTuMQ==,type:str]
  version: 3.13.1
