apiVersion: v1
kind: Secret
metadata:
    name: restic-profilarr
    namespace: kube-apps
stringData:
    #ENC[AES256_GCM,data:v/rqDm3BYT1G7Li+NAfj5WZWJw==,iv:piXYLG+01JqYS+G6/ZFggNVsZt5NgDuv6EUU6Oh+sbQ=,tag:CqqT7wJgEXOLSgrJhQClqw==,type:comment]
    RESTIC_REPOSITORY: ENC[AES256_GCM,data:g0sEJUhef0XdshW9gr5rJ3X5eRwbi6Kn3XJub6USfm1sK7fD8v8E0SRToDdD6pfRvtPBWY+RKPkM1Q5fj7pwdTOF3QI=,iv:hu4p1793h0/FsxpRaqbEV03ozY+9po+7AuuuVAKBWx0=,tag:Hk8K/qsBhahIPUoslZP6Lg==,type:str]
    #ENC[AES256_GCM,data:7AAND4QuKTwkUSA1Hn4d+UevZCQLjxYD+SSJ8DPi,iv:8InNm5Sxaxa7IFYYwM7OapFI1e7rGa8rO2tb+2yFcR8=,tag:HjMSFBVAf8PcJBq9ybLD/w==,type:comment]
    RESTIC_PASSWORD: ENC[AES256_GCM,data:WE/I1g==,iv:6Xo1/vSxl1jz8RCccyIFrl86D4Zn0dpxwUgzL3x4gmc=,tag:n5SMBtWFrmy7DU5N+EnY3g==,type:str]
    #ENC[AES256_GCM,data:6qoNbUfJ3LiIi6fwteXU0HC+z8may4qfZZTkKLxX9eFBmdLtPbQm4Hg=,iv:D5OoPq6eaw17tQ46G8RrMuBCY/BSYp5RFuORoMoSY6I=,tag:E7AwYNjDM9ajMljWjrCDRQ==,type:comment]
    #ENC[AES256_GCM,data:6Y1g7+LbYEPbtwIK0fnbIh2quDXwYssJU084p8Um0Yf99F1vvy7Sk2+wAGWJRDEHABMbFEBAVWTgkQiFNgTyUYiXg0FHtQ==,iv:F2bvuONc6/OTU3aJvvGuVRRsAmkq0aXlOnH/SF/6L6A=,tag:UL4INNhPOK3S3K9mAlLqxA==,type:comment]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:aUU2rt7zmvdUpjBefd8quOSEydU=,iv:4hD0r80d8pXcQgTKjGwhk2+Oo85F0T7+pagNvDhtBnU=,tag:NhQmMoAIlwlgTRAq4+1Vyw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:OJBMlPdw2EuQwxbGYdrxgqiN5B4CnI/02/lifEPnfyr6sh+gYEqLdw==,iv:ehiT5AFqFi6T9ndoEi5VLgBdck6oXp+xoEAWPP8phEc=,tag:WJ/CVKNUyk75GJZavIfDPw==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZGUvMzJmKytPb2d5NG4x
            REo5ZEc4UDFwcmQxdnBRUUZIbDI2dzN4TFFZCnJrWjR4aUxoc2JqNVh4WjBTKzFI
            VFd4SlpTQVRxUnFiZjdxVnJ2MGFmS3MKLS0tIGp0L0xmMVkxWVJlaUFwTzlTazRt
            Tm9NYVNVZjUrZUFLbS9WQmNVcjFpVGsKrZyCYx3InSl9BAfOLP/8Nb4Bt9skNjmi
            ywg6GNEEN0qS/W/1TKVCwLZ/TAbbyeyKXWiq/WzCiDtxrNg0YWT35g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T18:24:01Z"
    mac: ENC[AES256_GCM,data:iE7RQObL8KG2eXzUVJkCk5igl5jhqDwC31GxCUqWHweUuxuSq2odJIpr5n3bOiwKYPiu16o11H37g1/xicmNbIuwxz1LiXGBJxgZK9+SSM2IQ7rxB8UYeC60Ib5N2FRkNnHIQDxHRVZ2ytQswE4lc8Dqh3UnW+WItGzs/ckHF2w=,iv:sIwf/EsleY75FjFMC/9l0pfrFPBgmWf9KppMnKHE0h4=,tag:fX6Rsn2KiyyYgCX/MSpWwg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.2
