---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plugin-barman-cloud
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: plugin-barman-cloud
  values:
    image:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud
      tag: v0.14.0@sha256:823a8893690980ba5830bbbb11196a35f695b0488db7d846abc33baebf32417c
    sidecarImage:
      registry: ghcr.io
      repository: cloudnative-pg/plugin-barman-cloud-sidecar
      tag: v0.15.0@sha256:06c78deca670525daa35fb1e5323159092785d11cf87b86217bdd5c679a41a84
    containerSecurityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      runAsUser: 26
      runAsGroup: 26
      capabilities:
        drop:
          - "ALL"
    podSecurityContext:
      runAsNonRoot: true
    resources:
      limits:
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    certificate:
      issuerName: letsencrypt-production
      # -- The duration of the certificates.
      duration: 1080h
      # -- The renew before time for the certificates.
      renewBefore: 120h
