apiVersion: v1
kind: Secret
metadata:
  name: kopia
  namespace: kube-system
stringData:
  #ENC[AES256_GCM,data:7AAND4QuKTwkUSA1Hn4d+UevZCQLjxYD+SSJ8DPi,iv:8InNm5Sxaxa7IFYYwM7OapFI1e7rGa8rO2tb+2yFcR8=,tag:HjMSFBVAf8PcJBq9ybLD/w==,type:comment]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:rNbz9w==,iv:9sMCJ9lVbob2BEKrxt58Hkb9g870FnbBHfIaeke7NSk=,tag:dn5KcAfMVzNkL0GAVRY2EQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:cVXkjvpSY/nTJru5Pgu8bevimjw=,iv:7TbtriIwxbKGLImI16arFnAzKrK0pEQj6SRQHACbqtU=,tag:fdiVC0+0Eg6TJUBoVHWjvA==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:4PDh7zleTBiYkL1VulQ1dFYYqUH3k31y9reDt/uuFhFG2NkVbL9Prw==,iv:2RTDdh9Zfoi8EF6Lk6pimBruyU9P6ieChkku06Vsgrk=,tag:dhVk5f8sBuh9KiXZdMxhNQ==,type:str]
  UI_USER: ENC[AES256_GCM,data:0zLvbhc=,iv:GwrGpOTKA/7l/eSw3tBX2+Ot9NMRp5Pe+oWAP+N+EOY=,tag:gk/9zH3oveJckoAHvPjNQQ==,type:str]
  UI_PASS: ENC[AES256_GCM,data:uUAFPoX4KjvDLagtqD8=,iv:389VexNTAFyaTVjRbA3ZszCBF/Am33gskrBXxl4kzmQ=,tag:kzkD32c6MP9TWSTUjuI3vw==,type:str]
  TEST: ENC[AES256_GCM,data:B0EGJA==,iv:91r2DrKIgi0MaWcUBhmru4s0zvX/0jBsS63e2vEYZ+Q=,tag:NGisg/AOjKvTBXx63/Nt4Q==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZGUvMzJmKytPb2d5NG4x
        REo5ZEc4UDFwcmQxdnBRUUZIbDI2dzN4TFFZCnJrWjR4aUxoc2JqNVh4WjBTKzFI
        VFd4SlpTQVRxUnFiZjdxVnJ2MGFmS3MKLS0tIGp0L0xmMVkxWVJlaUFwTzlTazRt
        Tm9NYVNVZjUrZUFLbS9WQmNVcjFpVGsKrZyCYx3InSl9BAfOLP/8Nb4Bt9skNjmi
        ywg6GNEEN0qS/W/1TKVCwLZ/TAbbyeyKXWiq/WzCiDtxrNg0YWT35g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-28T08:27:46Z"
  mac: ENC[AES256_GCM,data:DIlQ4G6zU61li8yO9rZPNOOcBj9KMsFsqd+/H6rne5sCN50LxjnWp05kx2UzYIkjMnSCR0pOIvMFvatzVOC4ZJmmNec7Hwwe5cMEnw9O89xo4dViBb52UxbGNNmklE54FM3TNtWZaixWxbvQDYjFj1pLF5KFGhL3QCNkuIOCfNs=,iv:BP62rldIINGkrQkkXdrCn6bhNebhzt/9ovXbGCVruOU=,tag:OGMxL+iBuWSWzh5ikGu8pw==,type:str]
  version: 3.13.1
