apiVersion: v1
kind: Secret
metadata:
  name: kopia
  namespace: kube-system
stringData:
  #ENC[AES256_GCM,data:7AAND4QuKTwkUSA1Hn4d+UevZCQLjxYD+SSJ8DPi,iv:8InNm5Sxaxa7IFYYwM7OapFI1e7rGa8rO2tb+2yFcR8=,tag:HjMSFBVAf8PcJBq9ybLD/w==,type:comment]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:rNbz9w==,iv:9sMCJ9lVbob2BEKrxt58Hkb9g870FnbBHfIaeke7NSk=,tag:dn5KcAfMVzNkL0GAVRY2EQ==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:1PsH/Oq+0vqQpkJJ9u3a3hTk+7A=,iv:8rK3P0PcHL7W5q3+MrZCRBtF8EHMDDSf5QZKxhqwjVQ=,tag:a3AFhUA5DIUApxNXFttoAg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:qDsTHha/JBBTHfbaiea8CZkVYNDTnM+XacQ6dqvepAiEbPK8UiTZuQ==,iv:220GD64l+FsF7hiYyhKOsXcfs2kvL28Xri2cwKgW5go=,tag:S2GnHmsb+vnZEIlP+LVd0g==,type:str]
  UI_USER: ENC[AES256_GCM,data:0zLvbhc=,iv:GwrGpOTKA/7l/eSw3tBX2+Ot9NMRp5Pe+oWAP+N+EOY=,tag:gk/9zH3oveJckoAHvPjNQQ==,type:str]
  UI_PASS: ENC[AES256_GCM,data:uUAFPoX4KjvDLagtqD8=,iv:389VexNTAFyaTVjRbA3ZszCBF/Am33gskrBXxl4kzmQ=,tag:kzkD32c6MP9TWSTUjuI3vw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZGUvMzJmKytPb2d5NG4x
        REo5ZEc4UDFwcmQxdnBRUUZIbDI2dzN4TFFZCnJrWjR4aUxoc2JqNVh4WjBTKzFI
        VFd4SlpTQVRxUnFiZjdxVnJ2MGFmS3MKLS0tIGp0L0xmMVkxWVJlaUFwTzlTazRt
        Tm9NYVNVZjUrZUFLbS9WQmNVcjFpVGsKrZyCYx3InSl9BAfOLP/8Nb4Bt9skNjmi
        ywg6GNEEN0qS/W/1TKVCwLZ/TAbbyeyKXWiq/WzCiDtxrNg0YWT35g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-03T21:43:30Z"
  mac: ENC[AES256_GCM,data:Z4rS1lPQDRxFcedhLCixKERJcAnbi23+xhpIMJXfthsFRW/KNyhIw9hccvOv/HjuQQF6Pq7lWWMTyXw6DEukqinENeP4Q2Gi4aX4e03VPPPD5KUYFZ9hR9VpNf1gzXdD1zP0ZvUUoOVQgGBtJ/kNCYGd9KpWl6MVV5ajOGZp+HE=,iv:RkZqRAqu9qwjmcUV/0UfNJFes7gDFDnWXnVNw26a5TE=,tag:7oZA03QZzFBPgxMKRJlCxw==,type:str]
  version: 3.13.1
