---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bernd-schorgers/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: ownfoil
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: ownfoil
  values:
    defaultPodOptions:
      securityContext:
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: a1ex4/ownfoil
              tag: 2.3.0@sha256:d3f7c09ea450b64479dc57ada98d46b4ca72ac5016e54ed7f660e7b43d82ce39
            command: ["python", "/app/app.py"]
            securityContext:
              runAsNonRoot: false
              runAsUser: 568
              runAsGroup: 568
              allowPrivilegeEscalation: true
              readOnlyRootFilesystem: false
              capabilities:
                add:
                 - SYS_ADMIN
            resources:
              requests:
                cpu: 150m
                memory: 256Mi
              limits:
                memory: 1024Mi
            env:
              - name: USER_ADMIN_NAME
                secretKeyRef:
                  name: ownfoil
                  key: user
              - name: USER_ADMIN_PASSWORD
                secretKeyRef:
                  name: ownfoil
                  key: pass

    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: &port 8465
    route:
      app:
        hostnames: ["eshop.${SECRET_DOMAIN}"]
        parentRefs:
          - name: internal
            namespace: network
            sectionName: http
        rules:
          - backendRefs:
              - identifier: main
                port: *port
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: ownfoil-config
        advancedMounts:
          main:
            main:
              - path: /app/config
                subPath: config
              - path: /app/data
                subPath: data

      games:
        type: persistentVolumeClaim
        existingClaim: ownfoil-data
        advancedMounts:
          main:
            main:
              - path: /games
