---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/volsync.backube/replicationsource_v1alpha1.json
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: ownfoil-backup
spec:
  sourcePVC: ownfoil
  trigger:
    schedule: "0 */12 * * *"
  restic:
    accessModes:
      - ReadWriteOnce
    cacheAccessModes:
      - ReadWriteOnce
    cacheCapacity: 1Gi
    copyMethod: Snapshot
    moverSecurityContext:
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
    repository: restic-ownfoil
    pruneIntervalDays: 7
    retain:
      hourly: 1
      daily: 1
    volumeSnapshotClassName: proxmox-snap
