apiVersion: v1
kind: Secret
metadata:
  name: ownfoil
stringData:
  user: ENC[AES256_GCM,data:EfmLsGw=,iv:WDybL7BvsH30boBUtTKcxE5QgvYVoDzqTqoFDYVBqmE=,tag:/5JYIBrgqmP4E0eSxQhAaw==,type:str]
  pass: ENC[AES256_GCM,data:+GQiy7is/yQMmYKmvVQ=,iv:v/UfBlB53nB8eTLa4Ogb0iIPJE+irpzkqtqQ/Myl6fY=,tag:8UD6nPnviI6MgA4yNnV79g==,type:str]
sops:
  age:
    - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArdFVDWlAyZW1SOGorOTZa
        Y214TWNpRDFlcTRzdlVNeExNcGFIWEk4SzI4ClRXR2dOdHRpZDlkbk1ERjl2WnU2
        a240N3I3c0srZzBxSVpJZkp5RjdGREkKLS0tIDlSbmwrS21xSFByTlVsNlVGbU5h
        NExoZ1hOamhuK2I0TnowTUI0STNSUFEKY3yucECXypuTHusHKSu7b3A9ilcbFcuN
        ux0H7nOVnHPZAi4X3AqBWLvSJ55QM8Y4aKrkSmUyjPbF8/PxZ9FLlg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-03-03T17:33:15Z"
  mac: ENC[AES256_GCM,data:YrJTFzVtEZiv23Nr5EyBUTnTo1wELwUMzuPeTG4VewQy/tURH7C+ppmkIXAZTp/ZUS9PPkmc2TYZ1CWOd39Xog5TQTIGrhUgGrusQFVj2NGb2RdXxAAk2UsPS5TfF5iOqzp7WIR5u1flfi5P9mK2M0XwJ+BySvFyD0dYp1x422Y=,iv:tEQrlufCE+BF9bK+L25znVGAF+OI6Z61IEbjlaesTFM=,tag:AkaYZntn5bschlajxBG2nw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.12.1
