# yaml-language-server: $schema=http://192.168.1.170:5000/api/config/schema.json
auth:
  enabled: false
tls:
  enabled: false
mqtt:
  host: nanomq.db.svc.cluster.local
  user: admin
  password: "{FRIGATE_MQTT_PASSWORD}"
cameras:
  living:
    enabled: true
    ffmpeg:
      output_args:
        record: preset-record-generic-audio-aac
      inputs:
        - path: rtsp://127.0.0.1:8554/sub
          input_args: preset-rtsp-restream
          roles:
            - detect
        - path: rtsp://127.0.0.1:8554/main
          input_args: preset-rtsp-restream
          roles:
            - record
    onvif:
      host: 192.168.1.161
      port: 2020
      # doesn't support yet env for onvif, maybe 0.18 will support
      user: living
      password: segasega
    detect:
      width: 1280
      height: 720
    live:
      streams:
        Main Stream: main
        Sub Stream: sub
record:
  enabled: True
  detections:
    retain:
      days: 2
      mode: motion
version: 0.17-0
detectors: 
  cpu:
    type: cpu
model:
  model_type: yolo-generic
  width: 640 # <--- should match the imgsize set during model export
  height: 640 # <--- should match the imgsize set during model export
  input_tensor: nchw
  input_dtype: float
  path: /config/model_cache/yolo.onnx
  labelmap_path: /labelmap/coco-80.txt
go2rtc:
  streams:
    sub:
      - rtsp://living:segasega@192.168.1.161:554/stream2
      - "ffmpeg:sub#audio=aac"
    main:
      - rtsp://living:segasega@192.168.1.161:554/stream1
      - "ffmpeg:main#audio=aac"
  webrtc:
    candidates:
      - 127.0.0.1:8555
