apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-token: ENC[AES256_GCM,data:pJbwvSMe+kLDRcy4Cq/IL5u6zMXs2Gi98nYKiTc/qm0QtmEGpaXuag==,iv:AGYwdEcilSofjyZy1Xvujm4AENI04haUpfxgNNUAVGs=,tag:QfAxqmXZ6zfAGz6e1O4XDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmLzhOaTljUkdCdW9zY2J4
        Q3JPWmlsdkQ2SW5jdTFBeHNJVUQ3aFU2eXlrClNIS3dJVCtIZ3FqcDNiUEZiU2Vr
        NW44NkN0NFVRUEJkcjZvemhuUWtuWkEKLS0tIDlhS0dUZ1hnMG94WjVIU05TdHl1
        clVLY1AwUjVBQWYxMnVLdHVpVDVGL0EK7UMxA8Y3MicxBl1aoePi8whOGrFz2ytP
        uac6V6XXTu+WlLrnwyZXIkkwZrwlqYw7ExMPT81S2hTH/odOSdkQ0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T15:22:24Z"
  mac: ENC[AES256_GCM,data:+L3vZKgXEjPF29w/9WkHJOps9FkPpN+ZMIdlgl9t2pbIZhQ6XoEx6TOrTZZKg4bqQa578n2RHhDWLGMygwbRo5svNPstWEqA/asrF1+0MtcLogB4YmDlgGMbRqc+d35AWGmepVnuvW5VR+ctuxavPDv6oGAsmo29VSJSz6Dqpho=,iv:E8040slL7kw2++DlCJWfVZtGtWREcZt/4UUr0Rc8j3s=,tag:VSuP2A8o55lM0EWyr5ow2w==,type:str]
  mac_only_encrypted: true
  version: 3.13.2
