---
# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
  namespace: cert-manager
stringData:
  api-token: ENC[AES256_GCM,data:pJbwvSMe+kLDRcy4Cq/IL5u6zMXs2Gi98nYKiTc/qm0QtmEGpaXuag==,iv:AGYwdEcilSofjyZy1Xvujm4AENI04haUpfxgNNUAVGs=,tag:QfAxqmXZ6zfAGz6e1O4XDA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmLzhOaTljUkdCdW9zY2J4
        Q3JPWmlsdkQ2SW5jdTFBeHNJVUQ3aFU2eXlrClNIS3dJVCtIZ3FqcDNiUEZiU2Vr
        NW44NkN0NFVRUEJkcjZvemhuUWtuWkEKLS0tIDlhS0dUZ1hnMG94WjVIU05TdHl1
        clVLY1AwUjVBQWYxMnVLdHVpVDVGL0EK7UMxA8Y3MicxBl1aoePi8whOGrFz2ytP
        uac6V6XXTu+WlLrnwyZXIkkwZrwlqYw7ExMPT81S2hTH/odOSdkQ0w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-20T14:08:22Z"
  mac: ENC[AES256_GCM,data:c4BuLHJVoQqaiN5F+JC35abjeBPm5hi+xokirwsbv8rPw9If51WBw4KgfonAToZ1i7Y+U9NrxVzBdjmQG5vnrPyTSBynyevKGu0d1onUU9sXBSyESfZTnntyVrhXfBpUeuwG4yjDraDhKAo8oOTGGiBepgUTCtWnj6mb2kvggTU=,iv:lIzg77Wpi+c/j/r6hNsJbdvZ/01vwoRNmbaxCfK5b3g=,tag:/bbhdBx/id0bli9qx3WveA==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
