apiVersion: v1
kind: Secret
metadata:
  name: clients
  namespace: kube-system
stringData:
  oidc.client.immich.plain: ENC[AES256_GCM,data:gfQbt+POZgsO50ODXRiqBjEHCVhNz/AmuGpFiPQX2d4EML9o2159D+HGnw4k6k5IFmCEA4tgyvfLaCaVnC3G+7YjuRnnmz7Q,iv:DIy5rvYyG25voNJl7YXPNfcbCiiOyA40ER9Q2TvQmGk=,tag:p9hUGif60Cg/nZfQpmqYyA==,type:str]
  oidc.client.nextcloud.plain: ENC[AES256_GCM,data:4Z9rJyCGrm5m/QSsI8gL7wjAF5AAtcqwaWw5yHCllkV9D5v7MfPJL5uO8hbZnU6mO2ux9R9ChV73/4KwSAuZmD4TsuwhOXZX,iv:t6ahApqkRIsmGGTZXglt/4dadghY4YnBgi2/Sp70nwI=,tag:ITa1FpekXOC7lnmgfViPTw==,type:str]
  oidc.client.silo.plain: ENC[AES256_GCM,data:duxR8sKOe5S2tRE7MYalrWXGpqh9XB5nw4p9VYXedYbJydBZ4fzzCzKZ2CppGQHBoYTgdQxsrB8ih1jWXTJBFluyfH7b57Hk,iv:/H449mtDTI6s8/C9TCJ2a2QE54HrHNxZr8zvPLSXQLo=,tag:3sVmuK1otx38DIuA8ytQcg==,type:str]
  oidc.client.sftpgo.plain: ENC[AES256_GCM,data:zvwDil7en9ir870oENKts/45saW3wkm+yACT3ylTLzgCW7uQDIbAJmL4FIACcxyfgPzz9xZ28rKPkQiZ86HWIrKXiB1+Sedt,iv:+wdJ50rilACsjreEQ8Ng8ZVtG6IHLS/aPkjL7pnBpic=,tag:hG2JOjsg2KTCVu2HYyLdrA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2Nkk1bURSZW9JbGhXT0pr
        ZnZtcXpDTlpMdFVKa01mL0JsUWtENWN2V0ZRClNFcm1vNGJFV2NaWlVHdmxBaWk2
        dFo1OUU2MDBhaXBaVkw2QklDLzhScHMKLS0tIFNONCthdm92clVyMGxtcHhEczZG
        SXpHUnRza3NrcnRLejRvUndWaWxraUEK3Qa+jkDwKO/6Yl1DDe/EEaf8hqAdc/II
        hG0Vh0Tr++HOVfT7UBgPzCkoGIxZQYIAFXXKsEAWumUNjN51GmECvQ==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-10-09T18:16:51Z"
  mac: ENC[AES256_GCM,data:7+ExRFTl8m98yZXe8IkjNyf9/yuTDRcIRqhQltFXng1TafnsdcEMKVP2LemvPpT4JltKbY5tD8J4CgVRe/Zt8Fl5x49O/m3DP0/2CRrpiRlq56FthB97gKxNX5JzuSQ2NijxQFluVuhp9Sl0udP+E0c8LQzT00k28yIm4ehSQ/o=,iv:pHuXtaoaWTm/YbXrrCaMyzrfUMW9pEFP7h81QSq/X7g=,tag:PEnWA4uXTBKIa8aRuKU8xQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
