apiVersion: v1
kind: Secret
metadata:
  name: cross-seed
  namespace: media
stringData:
  config.js: ENC[AES256_GCM,data:LVbS/Q==,iv:jdZOHhIceHNZgqQEmg52vIrzBLudWgKSccw/jsGn5SQ=,tag:7S53FBJex9dXq1EPg30Zag==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRZDJNVVlISUZaQjZHQ2RO
        VmpRTjA5ZkprM3hBd2Mwcll3eVlqWERLMUFnCnVack83Tjd5a3Ixb1g1Vjg2Q2hP
        MlhwZUcvZmo2c0tpb0Zma3VNaGYzcUUKLS0tIHBkV3hNR3RNRlRieUx5VVFzeVFv
        Zi91WXFXa1FveURvK3pXNHkxdVRZZkEKl0ovqnIq9UuxXsw51vt+sKE8jjtLWRBZ
        EE4oN0e/m/91cflMj2ft25LraQxlLNUHOFRVK6c8z+7SspD9FDdC4w==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-06-14T12:10:29Z"
  mac: ENC[AES256_GCM,data:0TdFnOFXm8E0BSbVYFPyvrKjfrlTA3cTC+xfYawxjQ3HzbIC/YDVVSiXFIryv5+yq0E8L1ZQAzwHVDNekeoZB5xJDf/lX6xeV06dTsMPPpimibiK0aUzQ4y+8OXXfMifYr+c+TZvzglJbmU+gv+JVdg9B2fl9NN8uvDk/rEqiWg=,iv:nyBYPXu3NOvknni/q9hiiZK9RXN0n+iUmvYTu7df59U=,tag:jFFftkm1Ri4mAD6WkbK/LQ==,type:str]
  mac_only_encrypted: true
  version: 3.13.1
