apiVersion: v1
kind: Secret
metadata:
    name: garage-secret
stringData:
    GARAGE_RPC_SECRET: ENC[AES256_GCM,data:VNsfSIam,iv:iRzB6gNtOR9Zh5i9t9dBkmD5VnqkL/q4gyO5PJ/0K80=,tag:+kI5fJsh3o5kL4vcA0EN8Q==,type:str]
    GARAGE_METRICS_TOKEN: ENC[AES256_GCM,data:opw2ZJ75,iv:I7irsFqQzXPc0mpo55XPnCS4rPMh3ELItDbyDV6f2Es=,tag:eyXUJqkcLtDPwnPzNpQTng==,type:str]
    GARAGE_ADMIN_TOKEN: ENC[AES256_GCM,data:CllvmrQy6eEEQwFn,iv:O2Co+XwX9YKf5zvb98BZ+MajfuOIdipTpeG451xYA5I=,tag:YJYV+K8V8ACE4s0vuZNnaA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcXd3ZDZMM3Q0elBCaVZw
            VjR0S0tJa2ZMcWdrVDRCbWVoeGNQSkRRYzFVCkxtRkFQS2JQRFUrVmJlRHRRcS92
            SU5vRkN6eSs2bitzMXBVS3F3cFJ0eGsKLS0tIElpN084SGpjN1pZTEdVZ3BNZEhZ
            SGpSdFZnc1lRTk1rd042UzZ0c1VLQ0kKQnaIe3uAD6lvV1hpZroDhK//1LgDpDCv
            kzTsY+WedCM0AvWq6FpgwGRBqBCzmrUxjCHe/6efKFLOc4+NXmIYpw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-05-17T09:44:21Z"
    mac: ENC[AES256_GCM,data:U64zmdo5F8sLFkLst+hHb4WhrhTttnrL5YxShhB6iNr7lI8pZkBeDIN4SZT0Ct7wf/SQPnLFtMDJcG+dUnuh9ZDII8DZ4xxRHCFheP7LfYVFbrb7ziqePAPXhFydb+gqG63mmIqn7Iz5QwyD+rrH41s/cLPFIEterxgUA078seI=,iv:FQHfgfJUlbqqN9f5hYN1WTiIT7WIiT5by9WrVv7v4UU=,tag:DV3WdscJj7zLmTy/A0Ad3Q==,type:str]
    version: 3.13.1
