---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: storage-system
components:
  - ../../components/common
resources:
  - ./kopiur/ks.yaml
  - ./openebs/ks.yaml
  - ./rustfs/ks.yaml
  - ./snapshot-controller/ks.yaml
  - ./namespace.yaml
