apiVersion: v1
kind: Secret
metadata:
  name: kopia
  namespace: storage-system
stringData:
  #ENC[AES256_GCM,data:7AAND4QuKTwkUSA1Hn4d+UevZCQLjxYD+SSJ8DPi,iv:8InNm5Sxaxa7IFYYwM7OapFI1e7rGa8rO2tb+2yFcR8=,tag:HjMSFBVAf8PcJBq9ybLD/w==,type:comment]
  KOPIA_PASSWORD: ENC[AES256_GCM,data:SnfkyKE5iXCt8/09hwvcc8RnOFEhNySofPMDmiAc6Jg=,iv:fmZIcE/dQjKW/pJlBP1NN+ylR+9/cdgptWG7aAHFhhI=,tag:Eu3gcsSlAm2DVKml5HFt8A==,type:str]
  KOPIA_WEBDAV_USERNAME: ENC[AES256_GCM,data:8QHC2IK024AetJy5zIWor+YUIBrY7rzXzA==,iv:YjSYPKLUnb49CFqy8jKa6zamh+c3bRKYeKu0b3uuRxA=,tag:yfEONE5HJN1BTvh2hyue5Q==,type:str]
  KOPIA_WEBDAV_PASSWORD: ENC[AES256_GCM,data:8waYFVyu81BCGC1JOVNO,iv:OlVN0cFB5QsKZYwba5bq8EwvkImRwz7P4rbqoBrSSbY=,tag:GWS/BmsvuVU9lQ1mbYAqZg==,type:str]
  AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pw/VXKB+70f5RKC7iJhpI+S6VSg=,iv:PP9WicEcQdkRVwpYgKeYZkkXGJxmotVoxCFVo3F7HeM=,tag:nrbH2+VnQh8S+KHzruF8cg==,type:str]
  AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:moZCxYfO7vU91hZKRW8hP6hdvjxcfvO9q1P3jU6DDNn6Cu3bJ+2oRQ==,iv:sd6lT7fpmvSezUnqY5SCC4Dn6GZ30MJwlTpgVQXv+Mc=,tag:dndQk/XKKDfOIvd+mGuhIA==,type:str]
  UI_USER: ENC[AES256_GCM,data:0zLvbhc=,iv:GwrGpOTKA/7l/eSw3tBX2+Ot9NMRp5Pe+oWAP+N+EOY=,tag:gk/9zH3oveJckoAHvPjNQQ==,type:str]
  UI_PASS: ENC[AES256_GCM,data:uUAFPoX4KjvDLagtqD8=,iv:389VexNTAFyaTVjRbA3ZszCBF/Am33gskrBXxl4kzmQ=,tag:kzkD32c6MP9TWSTUjuI3vw==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4ZGUvMzJmKytPb2d5NG4x
        REo5ZEc4UDFwcmQxdnBRUUZIbDI2dzN4TFFZCnJrWjR4aUxoc2JqNVh4WjBTKzFI
        VFd4SlpTQVRxUnFiZjdxVnJ2MGFmS3MKLS0tIGp0L0xmMVkxWVJlaUFwTzlTazRt
        Tm9NYVNVZjUrZUFLbS9WQmNVcjFpVGsKrZyCYx3InSl9BAfOLP/8Nb4Bt9skNjmi
        ywg6GNEEN0qS/W/1TKVCwLZ/TAbbyeyKXWiq/WzCiDtxrNg0YWT35g==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-05T18:32:34Z"
  mac: ENC[AES256_GCM,data:AUAloKYP/FAHAst5f0uRQBVS1RMwlLNW/qsv2Rw7cdTUzdecaBf9i430ZURsRi33XejZ/UCRfCWyTtmyjkj4kRYzY5zAN/WJ0H9Y+05luQKmavpzcOjQLaPD9AXcQj+BfQN8JdrVQxKvLl0s7JzUiQSqdJApGO3rEkCcpWkEEtA=,iv:iVijSVF3AVvhUHO3moVdyHZjovGtlCEjv0FYkAa5mrE=,tag:1BFDQvbjsnTpszY6YeeFaA==,type:str]
  version: 3.13.2
