---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bernd-schorgers/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: filebrowser
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 3.7.3
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        strategy: Recreate
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          main:
            image:
              repository: docker.io/filebrowser/filebrowser
              tag: v2.40.2@sha256:2cd16c5d480f68e79dd3b222c6b0ec855b755a4f61b45fdaa5c3cac0d4f8d8e8
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 150m
                memory: 128Mi
              limits:
                memory: 256Mi
            env:
              FB_DATABASE: /config/filebrowser.db
              FB_CONFIG: /config/filebrowser.json
              FB_ROOT: /data
              FB_LOG: stdout
              TZ: ${CONFIG_TIMEZONE}
              FB_PORT: &port 80
    service:
      main:
        controller: main
        type: ClusterIP
        ports:
          http:
            port: *port
    ingress:
      # Configure an Ingress for the main application
      main:
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
          cert-manager.io/cluster-issuer: "letsencrypt-production"
        hosts:
          - host: &host "filebrowser.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  identifier: main
                  port: http
        tls:
          - hosts:
              - *host
            secretName: fb-cert
    persistence:
      config:
        type: persistentVolumeClaim
        existingClaim: filebrowser-config
      data:
        type: nfs
        server: 192.168.1.150
        path: /mnt/storage/media
