apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: proxmox-secret
    namespace: storage-system
stringData:
    config.yaml: ENC[AES256_GCM,data:7V6+DIYQqHYiFysJeO9qIV64jlD43XCIXvmw1cxrPzXBmMj3QXVNHm43bBGyOBv0Pw6+YpAjUTKulApS23IUowSNPxw+togfHjKzyuh5N74PT6Hh+lz0v0IMkHKNi5esoKbpyKkCj2Vt9d6UDKWtKIL6mE84tpCXdrcmHJNVXuKQV4LSWN6zth0iCeMXYyfxv7lUfF0FR5adK4RNHXzZn2LQm/zZmDGKIqSv8a/yvMrgOb0VDUmWSfZw8kuwP+NYQozLX0TQ/BQ5ub+m9SDV+cJmJwChD5YRRt1XOCu53E7TgbmDoTLdZp6Lue2FbEF+ft91R++SVCpYvOi1K3aMcat3f+nDogadwnfWHQUvbOAVWjCDqRXc3FdR2rpVeF+FAVlTe2zMKz9RdlI1zTbL1A==,iv:RFJxjc+xHOLVhWLccSQ4oL9Z0s3w6GV4lpzo61bLcoQ=,tag:iSpU7mJ3PL54oT5S6w2xNw==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcGRtZVNUZS9OVzVoUDYz
            MGhpOUtTRnY3ZVFyaXFnS21BT1k0Q09oU0JRCjllbm9FT2lJQ0lPUFN5dEc0YlJm
            ZWpsSTVPR3Yxc3FyMURtQUZNRFZ4Y1UKLS0tIDdid0pmQjBteU00ZzY3Ym9xajgv
            bWlWOFVEMTNSN0VEd2ZmQjJ1dmpBOVUKF+MUs4dJNYMDNsB4t/5wdkWMQEz4pPmy
            slcG7NPo94S2YsPdFGK1pKGXr7mM/kN48E2106X5Lo92TwBdfP8xAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T23:20:46Z"
    mac: ENC[AES256_GCM,data:5xUAoGS6utPKC2J44gem4oD4GQW9iEE7ozpeBlKtyWUPhyPnA7I2qN/6fF6IUnaP9wV3kAO5JR91R0cNyL3TIeFdhxzIur/jCb+US0P8By2dwt/OTgKNaisgbOsth6+wJLLKrksVgKdRdIAgK9ngmJWUWet7mW9+8KdBptXZ8q0=,iv:YPLXBodgxoerd8cqQIHNjmrLewCmna8ncih/zBEj4nE=,tag:XWgwwhQ27WORLztGOHyOUA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
