apiVersion: v1
kind: Secret
type: Opaque
metadata:
    name: proxmox-secret
    namespace: storage-system
stringData:
    config.yaml: ENC[AES256_GCM,data:et4JEVwFxhcJzVHDRJTwWdqrfQkgXeCk1o5bZXKj6TYyf4h9E6zUt5oMzC3HqcyX33NBUHVk9oLu4RqRdDKddpBucrsnTawnUOWLCTFEI2xaoI07AktYkxOEAn5WthUqnsgOcQAFYoQqa3hAMaqUIb179BilO6s29we7JspnfmRsagBE/QoBdJIpXB5vzdMSev8CGuaAIQ6tLP3CHantmAMjt3V5Qcbgv4MKexSANetKgJ5fWxXn0QmO1gQRRGPiTOmpZxp+U8Og3VKXZ9OCawkOLTKgGn0PNVeiqt4eHrSh1GdrvryqaBe4LtcTIR610EXItu1I7xo2r7ho7OhSlLsjGDPQpQxdo0TEfhK5ZLTj8IKDTyAFhgBgrWXuI8wV6TM7cHHnzlddfXnPdXB0SwIZF2UmTiQijv4nVw==,iv:LTPt+2Iyu5iiBtvnqjtircvuvd8kl5FrnJK3GcLGx+U=,tag:asW+mD87xhO1E62KQ0rzHg==,type:str]
sops:
    age:
        - recipient: age1k5cr4cvs4atdm3gse77vq4glnv9q49gq5wl49p9806gfyfld7p3setz3tw
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtcGRtZVNUZS9OVzVoUDYz
            MGhpOUtTRnY3ZVFyaXFnS21BT1k0Q09oU0JRCjllbm9FT2lJQ0lPUFN5dEc0YlJm
            ZWpsSTVPR3Yxc3FyMURtQUZNRFZ4Y1UKLS0tIDdid0pmQjBteU00ZzY3Ym9xajgv
            bWlWOFVEMTNSN0VEd2ZmQjJ1dmpBOVUKF+MUs4dJNYMDNsB4t/5wdkWMQEz4pPmy
            slcG7NPo94S2YsPdFGK1pKGXr7mM/kN48E2106X5Lo92TwBdfP8xAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-04T23:16:46Z"
    mac: ENC[AES256_GCM,data:onSpv3G/GjDApr7hPerhFmvxXdqF7xdKGSxETpW+ZDkoNLdCksJl8Z6JzxH8IyjQiAM8+Osjaw2GVi1hhinVAljbk07VbhJ0znsgVZTC4/hSXa+HGxpbZKxGVbVw4NDPZ3omZB18OUJ0r7NGXQV5VekARPWlibMG7k8UCs6Ntfo=,iv:SuDfBZ8eSZnlmqr8GVfUtO2GBSmIMDK3zZYSZSXGVCk=,tag:08zASU++TuQ+ctjGZwCS/Q==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.12.2
