# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: proxmox-csi
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: proxmox-csi
  values:
    createNamespace: false
    logVerbosityLevel: 2
    existingConfigSecret: proxmox-secret
    storageClass:
      - name: proxmox-zfs
        storage: apps
        storageFormat: raw
        reclaimPolicy: Delete
        fstype: ext4
        cache: directsync
        ssd: true
        aio: native
        mountOptions:
          - discard
          - noatime
        replicate: false
    node:
      podSecurityContext:
      runAsNonRoot: true
      runAsUser: 568
      runAsGroup: 568
      fsGroup: 568
      fsGroupChangePolicy: OnRootMismatch