kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: dcsi-snap
  annotations:
    snapshot.storage.kubernetes.io/is-default-class: "true"
driver: csi.proxmox.sinextra.dev
deletionPolicy: Delete
